import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

/// Lightweight localization facade used while legacy screens are migrated.
///
/// Keeping the catalogue in Dart makes the v2 foundation immediately usable
/// without coupling domain code to Flutter's generated localization classes.
class AppLocalizations {
  const AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = <Locale>[
    Locale('vi'),
    Locale('lo'),
    Locale('en'),
  ];

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    final value = Localizations.of<AppLocalizations>(context, AppLocalizations);
    assert(value != null, 'AppLocalizations is not registered in MaterialApp.');
    return value!;
  }

  static const _shellVi = <String, String>{
    'nav.home': 'Trang chủ',
    'nav.modules': 'Phân hệ',
    'nav.create': 'Thêm mới',
    'nav.reports': 'Báo cáo',
    'nav.profile': 'Cá nhân',
    'home.greeting': 'Xin chào',
    'home.farmUnavailable': 'Chưa chọn trang trại',
    'home.kpi': 'Chỉ số chính',
    'home.quickActions': 'Truy cập nhanh',
    'home.farmOverview': 'Tổng quan trang trại',
    'home.recentActivity': 'Hoạt động gần đây',
    'kpi.parcels': 'Lô đất',
    'kpi.seasons': 'Mùa vụ',
    'kpi.tasks': 'Công việc',
    'kpi.alerts': 'Cảnh báo',
    'modules.title': 'Phân hệ',
    'modules.production': 'Sản xuất & đồng ruộng',
    'modules.resources': 'Nguồn lực',
    'modules.finance': 'Tài chính & chi phí',
    'modules.support': 'Quản lý & hỗ trợ',
    'module.parcels': 'Lô đất',
    'module.seasons': 'Mùa vụ',
    'module.productionLogs': 'Nhật ký sản xuất',
    'module.harvest': 'Thu hoạch',
    'module.employees': 'Nhân sự',
    'module.machines': 'Máy móc',
    'module.warehouse': 'Kho vật tư',
    'module.fuel': 'Nhiên liệu',
    'module.costs': 'Chi phí sản xuất',
    'module.finance': 'Tài chính',
    'module.resources': 'Máy móc & nhân sự',
    'module.tasks': 'Công việc',
    'module.ai': 'AI trợ lý',
    'module.cloud': 'Đồng bộ Cloud',
    'quickCreate.logs': 'Nhật ký',
    'quickCreate.harvest': 'Thu hoạch',
    'quickCreate.costs': 'Chi phí',
    'quickCreate.employees': 'Nhân sự',
    'quickCreate.machines': 'Máy móc',
    'quickCreate.tasks': 'Công việc',
    'quickCreate.other': 'Khác',
    'profile.title': 'Cá nhân',
    'profile.language': 'Ngôn ngữ',
    'profile.settings': 'Cài đặt',
    'common.unavailable': 'Chưa khả dụng',
    'common.empty': 'Chưa có dữ liệu',
    'common.open': 'Mở',
    'startup.error': 'Không thể khởi động AGRICO.',
    'parcel.boundaryRequired':
        'Hãy đo GPS hoặc nhập KML/KMZ trước khi tạo lô đất.',
    'export.unavailable': 'Không thể lưu hoặc mở tệp xuất.',
    'gps.permissionDenied': 'Quyền vị trí bị từ chối.',
  };
  static const _shellLo = <String, String>{
    'nav.home': 'ໜ້າຫຼັກ',
    'nav.modules': 'ໂມດູນ',
    'nav.create': 'ເພີ່ມໃໝ່',
    'nav.reports': 'ລາຍງານ',
    'nav.profile': 'ສ່ວນຕົວ',
    'home.greeting': 'ສະບາຍດີ',
    'home.farmUnavailable': 'ຍັງບໍ່ໄດ້ເລືອກຟາມ',
    'home.kpi': 'ຕົວຊີ້ວັດຫຼັກ',
    'home.quickActions': 'ເຂົ້າເຖິງດ່ວນ',
    'home.farmOverview': 'ພາບລວມຟາມ',
    'home.recentActivity': 'ກິດຈະກຳຫຼ້າສຸດ',
    'kpi.parcels': 'ແປງດິນ',
    'kpi.seasons': 'ລະດູການ',
    'kpi.tasks': 'ວຽກ',
    'kpi.alerts': 'ແຈ້ງເຕືອນ',
    'modules.title': 'ໂມດູນ',
    'modules.production': 'ການຜະລິດ ແລະ ພາກສະໜາມ',
    'modules.resources': 'ຊັບພະຍາກອນ',
    'modules.finance': 'ການເງິນ ແລະ ຕົ້ນທຶນ',
    'modules.support': 'ການຈັດການ ແລະ ຊ່ວຍເຫຼືອ',
    'module.parcels': 'ແປງດິນ',
    'module.seasons': 'ລະດູການ',
    'module.productionLogs': 'ບັນທຶກການຜະລິດ',
    'module.harvest': 'ເກັບກ່ຽວ',
    'module.employees': 'ພະນັກງານ',
    'module.machines': 'ເຄື່ອງຈັກ',
    'module.warehouse': 'ສາງວັດສະດຸ',
    'module.fuel': 'ນ້ຳມັນ',
    'module.costs': 'ຕົ້ນທຶນການຜະລິດ',
    'module.finance': 'ການເງິນ',
    'module.resources': 'ເຄື່ອງຈັກ ແລະ ພະນັກງານ',
    'module.tasks': 'ວຽກ',
    'module.ai': 'ຜູ້ຊ່ວຍ AI',
    'module.cloud': 'ຊິງ Cloud',
    'quickCreate.logs': 'ບັນທຶກ',
    'quickCreate.harvest': 'ເກັບກ່ຽວ',
    'quickCreate.costs': 'ຕົ້ນທຶນ',
    'quickCreate.employees': 'ພະນັກງານ',
    'quickCreate.machines': 'ເຄື່ອງຈັກ',
    'quickCreate.tasks': 'ວຽກ',
    'quickCreate.other': 'ອື່ນໆ',
    'profile.title': 'ສ່ວນຕົວ',
    'profile.language': 'ພາສາ',
    'profile.settings': 'ຕັ້ງຄ່າ',
    'common.unavailable': 'ຍັງບໍ່ພ້ອມ',
    'common.empty': 'ຍັງບໍ່ມີຂໍ້ມູນ',
    'common.open': 'ເປີດ',
    'startup.error': 'ບໍ່ສາມາດເລີ່ມ AGRICO.',
    'parcel.boundaryRequired': 'ກະລຸນາວັດ GPS ຫຼື ນຳເຂົ້າ KML/KMZ ກ່ອນ.',
    'export.unavailable': 'ບໍ່ສາມາດບັນທຶກ ຫຼື ເປີດໄຟລ໌.',
    'gps.permissionDenied': 'ສິດທີ່ຕັ້ງຖືກປະຕິເສດ.',
  };
  static const _shellEn = <String, String>{
    'nav.home': 'Home',
    'nav.modules': 'Modules',
    'nav.create': 'Create',
    'nav.reports': 'Reports',
    'nav.profile': 'Profile',
    'home.greeting': 'Welcome',
    'home.farmUnavailable': 'No farm selected',
    'home.kpi': 'Key indicators',
    'home.quickActions': 'Quick actions',
    'home.farmOverview': 'Farm overview',
    'home.recentActivity': 'Recent activity',
    'kpi.parcels': 'Parcels',
    'kpi.seasons': 'Seasons',
    'kpi.tasks': 'Tasks',
    'kpi.alerts': 'Alerts',
    'modules.title': 'Modules',
    'modules.production': 'Production & fields',
    'modules.resources': 'Resources',
    'modules.finance': 'Finance & costs',
    'modules.support': 'Management & support',
    'module.parcels': 'Land parcels',
    'module.seasons': 'Seasons',
    'module.productionLogs': 'Production logs',
    'module.harvest': 'Harvest',
    'module.employees': 'Employees',
    'module.machines': 'Machines',
    'module.warehouse': 'Inventory',
    'module.fuel': 'Fuel',
    'module.costs': 'Production costs',
    'module.finance': 'Finance',
    'module.resources': 'Machines & employees',
    'module.tasks': 'Tasks',
    'module.ai': 'AI assistant',
    'module.cloud': 'Cloud sync',
    'quickCreate.logs': 'Log',
    'quickCreate.harvest': 'Harvest',
    'quickCreate.costs': 'Cost',
    'quickCreate.employees': 'Employee',
    'quickCreate.machines': 'Machine',
    'quickCreate.tasks': 'Task',
    'quickCreate.other': 'Other',
    'profile.title': 'Profile',
    'profile.language': 'Language',
    'profile.settings': 'Settings',
    'common.unavailable': 'Unavailable',
    'common.empty': 'No data yet',
    'common.open': 'Open',
    'startup.error': 'AGRICO could not start.',
    'parcel.boundaryRequired':
        'Measure with GPS or import KML/KMZ before creating the parcel.',
    'export.unavailable': 'The exported file could not be saved or opened.',
    'gps.permissionDenied': 'Location permission was denied.',
  };

  static const Map<String, Map<String, String>> _catalogue = {
    'vi': {
      ..._shellVi,
      'app.name': 'AGRICO ERP',
      'app.tagline': 'Quản lý nông nghiệp thông minh',
      'auth.username': 'Email / Tên đăng nhập',
      'auth.password': 'Mật khẩu',
      'auth.forgotPassword': 'Quên mật khẩu?',
      'auth.signIn': 'ĐĂNG NHẬP',
      'auth.demoHint': '💡 (Nhấn nút để vào Demo, không cần mật khẩu)',
      'common.loading': 'Đang tải…',
      'common.retry': 'Thử lại',
      'common.cancel': 'Hủy',
      'common.save': 'Lưu',
      'error.unauthorized': 'Bạn không có quyền thực hiện thao tác này.',
      'error.permissionDenied': 'Bạn không có quyền thực hiện thao tác này.',
      'landParcel.create.success': 'Đã tạo lô đất.',
      'landParcel.update.success': 'Đã cập nhật thông tin lô đất.',
      'landParcel.error.notFound': 'Không tìm thấy lô đất.',
      'landParcel.geometry.invalid': 'Ranh giới lô đất không hợp lệ.',
      'landParcel.persistence.failed': 'Không thể lưu thay đổi lô đất.',
      'landParcel.boundary.verifiedConfirmation':
          'Ranh giới đã được xác minh. Hãy xác nhận trước khi thay thế.',
      'landParcel.boundary.replaceSuccess': 'Đã cập nhật ranh giới lô đất.',
      'landParcel.boundary.verifySuccess': 'Đã cập nhật trạng thái xác minh.',
      'boundary.verify.action': 'Xác minh ranh giới',
      'boundary.verify.confirmTitle': 'Xác minh ranh giới?',
      'boundary.verify.confirmMessage':
          'Sau khi xác minh, việc thay đổi ranh giới sẽ yêu cầu xác nhận rõ ràng.',
      'landParcel.gps.invalidSource': 'Nguồn đo GPS không hợp lệ.',
      'landParcel.import.previewReady':
          'Đã chuẩn bị bản xem trước nhập dữ liệu.',
      'landParcel.import.failed': 'Không thể đọc tệp KML/KMZ.',
      'landParcel.export.success': 'Đã xuất tệp KML/KMZ.',
      'landParcel.export.failed': 'Không thể xuất tệp KML/KMZ.',
      'landParcel.preview.warning': 'Hãy kiểm tra cảnh báo trước khi xác nhận.',
      'survey.household': 'Hộ gia đình',
      'survey.administrativeLocation': 'Địa chỉ hành chính',
      'survey.landUse': 'Mục đích sử dụng đất',
      'survey.landCondition': 'Hiện trạng đất',
      'survey.clearingStatus': 'Tình trạng phát quang',
      'survey.readinessStatus': 'Mức độ sẵn sàng',
      'survey.crop': 'Cây trồng',
      'survey.cropCondition': 'Tình trạng cây trồng',
      'survey.quantityUnit': 'Số lượng và đơn vị',
      'survey.record': 'Khảo sát đất',
      'survey.surveyor': 'Người khảo sát',
      'survey.attachment': 'Tệp đính kèm',
      'survey.validation.invalid': 'Dữ liệu khảo sát không hợp lệ.',
      'survey.persistence.failed': 'Không thể lưu dữ liệu khảo sát.',
      'common.all': 'Tất cả',
      'common.active': 'Đang hoạt động',
      'common.inactive': 'Ngừng hoạt động',
      'common.edit': 'Sửa',
      'common.remove': 'Xóa',
      'common.confirm': 'Xác nhận',
      'parcel.list.title': 'Danh sách lô đất',
      'parcel.list.empty': 'Chưa có lô đất.',
      'parcel.list.error': 'Không thể tải danh sách lô đất.',
      'parcel.detail.error': 'Không thể tải chi tiết lô đất.',
      'parcel.search': 'Tìm lô đất',
      'parcel.filter.active': 'Trạng thái',
      'parcel.filter.verification': 'Xác minh',
      'parcel.create.action': 'Tạo lô đất',
      'parcel.create.title': 'Tạo hồ sơ lô đất',
      'parcel.edit.title': 'Sửa hồ sơ lô đất',
      'parcel.code': 'Mã khoảnh',
      'parcel.name': 'Tên lô đất',
      'parcel.section.identity': 'Thông tin lô đất',
      'parcel.section.overview': 'Tổng quan',
      'parcel.section.boundary': 'Ranh giới và đo đạc',
      'location.country': 'Quốc gia',
      'location.province': 'Tỉnh',
      'location.district': 'Huyện',
      'location.village': 'Bản',
      'household.code': 'Mã hộ',
      'household.head': 'Chủ hộ',
      'household.phone': 'Điện thoại',
      'household.alternativeContact': 'Liên hệ khác',
      'geometry.areaM2': 'Diện tích m²',
      'geometry.areaHa': 'Diện tích ha',
      'geometry.perimeter': 'Chu vi',
      'geometry.centroid': 'Tâm thửa',
      'geometry.accuracy': 'Độ chính xác',
      'geometry.confidence': 'Độ tin cậy',
      'boundary.source': 'Nguồn ranh giới',
      'boundary.version': 'Phiên bản',
      'boundary.history.title': 'Lịch sử ranh giới',
      'boundary.reconciliation.required': 'Ranh giới thửa đất và dữ liệu không gian chưa khớp. Cần đối soát trước khi xuất KML/KMZ.',
      'boundary.reconciliation.eligible': 'Dữ liệu không gian đã khớp. Có thể gắn lại mã không gian còn thiếu cho thửa cũ.',
      'boundary.reconciliation.action': 'Gắn lại mã không gian',
      'boundary.reconciliation.confirm': 'Chỉ gắn mã không gian còn thiếu cho thửa này nếu kiểm tra lại dữ liệu vẫn khớp. Tiếp tục?',
      'boundary.reconciliation.success': 'Đã gắn lại mã không gian cho thửa đất.',
      'boundary.reconciliation.manual': 'Dữ liệu đã thay đổi hoặc chưa khớp. Cần đối soát thủ công.',
      'boundary.audit.visibleSummary': 'Tình trạng ranh giới của các thửa đang hiển thị',
      'boundary.audit.filter': 'Lọc theo tình trạng ranh giới',
      'boundary.audit.unlinked': 'Chưa liên kết không gian',
      'boundary.audit.consistent': 'Đã đồng bộ',
      'boundary.audit.repairableLegacyIdentity': 'Có thể gắn lại mã',
      'boundary.audit.needsReconciliation': 'Cần đối soát thủ công',
      'boundary.issue.missingLink': 'Thiếu liên kết với dữ liệu không gian.',
      'boundary.issue.identityMismatch': 'Mã không gian của thửa và liên kết không khớp.',
      'boundary.issue.missingFeature': 'Không tìm thấy đối tượng không gian đã liên kết.',
      'boundary.issue.wrongFeatureType': 'Đối tượng đã liên kết không phải thửa đất.',
      'boundary.issue.missingRevision': 'Không tìm thấy phiên bản không gian hiện tại.',
      'boundary.issue.invalidGeometry': 'Thiếu hình học đa giác trong đối tượng hoặc phiên bản.',
      'boundary.issue.missingBoundaryVersion': 'Không tìm thấy đúng một phiên bản ranh giới hiện tại.',
      'boundary.issue.boundaryReferenceMismatch': 'Phiên bản không gian tham chiếu sai lịch sử ranh giới.',
      'boundary.issue.boundaryGeometryMismatch': 'Hình học ranh giới của thửa và không gian không khớp.',
      'boundary.source.gps': 'GPS',
      'boundary.source.googleEarth': 'Google Earth',
      'boundary.source.manual': 'Thủ công',
      'boundary.source.cad': 'CAD',
      'boundary.source.imported': 'Nhập dữ liệu',
      'verification.draft': 'Bản nháp',
      'verification.measured': 'Đã đo',
      'verification.verified': 'Đã xác minh',
      'verification.rejected': 'Bị từ chối',
      'verification.confirm.title': 'Thay ranh giới đã xác minh?',
      'crop.empty': 'Chưa có cây trồng.',
      'crop.add': 'Thêm cây trồng',
      'crop.edit': 'Sửa cây trồng',
      'crop.type': 'Loại cây',
      'crop.quantity': 'Số lượng',
      'crop.unit': 'Đơn vị',
      'crop.condition.unknown': 'Chưa rõ',
      'crop.condition.planned': 'Dự kiến',
      'crop.condition.growing': 'Đang sinh trưởng',
      'crop.condition.healthy': 'Tốt',
      'crop.condition.stressed': 'Sinh trưởng kém',
      'crop.condition.harvested': 'Đã thu hoạch',
      'survey.empty': 'Chưa có khảo sát.',
      'attachment.empty': 'Chưa có tệp đính kèm.',
      'googleEarth.title': 'Google Earth',
      'googleEarth.import': 'Nhập KML/KMZ',
      'googleEarth.exportKml': 'Xuất KML',
      'googleEarth.exportKmz': 'Xuất KMZ',
      'googleEarth.open': 'Mở bằng Google Earth',
      'googleEarth.openSuccess': 'Đã mở tệp ranh giới.',
      'googleEarth.openUnavailable':
          'Không tìm thấy ứng dụng phù hợp để mở tệp.',
      'gps.preview.title': 'Xem trước đo GPS',
      'gps.start': 'Đo GPS',
      'gps.confirm': 'Áp dụng ranh giới GPS',
      'import.preview.title': 'Xem trước dữ liệu nhập',
      'import.warning.missingAgricoMetadata': 'Tệp không có metadata AGRICO.',
      'validation.required': 'Trường này là bắt buộc.',
      'attachment.addMetadata': 'Thêm ảnh / tài liệu',
      'landUse.agricultural': 'Nông nghiệp',
      'landUse.residential': 'Đất ở',
      'landUse.forest': 'Rừng',
      'landUse.pasture': 'Đồng cỏ',
      'landUse.mixed': 'Hỗn hợp',
      'landUse.other': 'Khác',
      'landCondition.unknown': 'Chưa rõ',
      'landCondition.unused': 'Chưa sử dụng',
      'landCondition.cultivated': 'Đang canh tác',
      'landCondition.degraded': 'Suy thoái',
      'landCondition.flooded': 'Ngập nước',
      'landCondition.other': 'Khác',
      'clearing.unknown': 'Chưa rõ',
      'clearing.notRequired': 'Không cần',
      'clearing.notStarted': 'Chưa phát quang',
      'clearing.partial': 'Một phần',
      'clearing.completed': 'Hoàn tất',
      'readiness.unknown': 'Chưa rõ',
      'readiness.notReady': 'Chưa sẵn sàng',
      'readiness.preparation': 'Đang chuẩn bị',
      'readiness.ready': 'Sẵn sàng',
    },
    'lo': {
      ..._shellLo,
      'app.name': 'AGRICO ERP',
      'app.tagline': 'ການຈັດການກະສິກຳອັດສະລິຍະ',
      'auth.username': 'ອີເມວ / ຊື່ຜູ້ໃຊ້',
      'auth.password': 'ລະຫັດຜ່ານ',
      'auth.forgotPassword': 'ລືມລະຫັດຜ່ານ?',
      'auth.signIn': 'ເຂົ້າລະບົບ',
      'auth.demoHint': '💡 (ກົດປຸ່ມເພື່ອເຂົ້າ Demo ໂດຍບໍ່ຕ້ອງໃສ່ລະຫັດ)',
      'common.loading': 'ກຳລັງໂຫຼດ…',
      'common.retry': 'ລອງໃໝ່',
      'common.cancel': 'ຍົກເລີກ',
      'common.save': 'ບັນທຶກ',
      'error.unauthorized': 'ທ່ານບໍ່ມີສິດເຮັດລາຍການນີ້.',
      'error.permissionDenied': 'ທ່ານບໍ່ມີສິດເຮັດລາຍການນີ້.',
      'landParcel.create.success': 'ສ້າງແປງດິນແລ້ວ.',
      'landParcel.update.success': 'ອັບເດດຂໍ້ມູນແປງດິນແລ້ວ.',
      'landParcel.error.notFound': 'ບໍ່ພົບແປງດິນ.',
      'landParcel.geometry.invalid': 'ເຂດແດນແປງດິນບໍ່ຖືກຕ້ອງ.',
      'landParcel.persistence.failed': 'ບໍ່ສາມາດບັນທຶກການປ່ຽນແປງໄດ້.',
      'landParcel.boundary.verifiedConfirmation':
          'ເຂດແດນນີ້ຖືກຢືນຢັນແລ້ວ. ກະລຸນາຢືນຢັນກ່ອນປ່ຽນແທນ.',
      'landParcel.boundary.replaceSuccess': 'ອັບເດດເຂດແດນແລ້ວ.',
      'landParcel.boundary.verifySuccess': 'ອັບເດດສະຖານະການຢືນຢັນແລ້ວ.',
      'boundary.verify.action': 'ຢືນຢັນເຂດແດນ',
      'boundary.verify.confirmTitle': 'ຢືນຢັນເຂດແດນບໍ?',
      'boundary.verify.confirmMessage':
          'ຫຼັງຈາກຢືນຢັນແລ້ວ ການປ່ຽນແທນເຂດແດນນີ້ຈະຕ້ອງມີການຢືນຢັນຢ່າງຊັດເຈນ.',
      'landParcel.gps.invalidSource': 'ແຫຼ່ງຂໍ້ມູນ GPS ບໍ່ຖືກຕ້ອງ.',
      'landParcel.import.previewReady': 'ກຽມຕົວຢ່າງກ່ອນນຳເຂົ້າແລ້ວ.',
      'landParcel.import.failed': 'ບໍ່ສາມາດອ່ານໄຟລ໌ KML/KMZ.',
      'landParcel.export.success': 'ສົ່ງອອກໄຟລ໌ KML/KMZ ແລ້ວ.',
      'landParcel.export.failed': 'ບໍ່ສາມາດສົ່ງອອກ KML/KMZ.',
      'landParcel.preview.warning': 'ກະລຸນາກວດຄຳເຕືອນກ່ອນຢືນຢັນ.',
      'survey.household': 'ຄົວເຮືອນ',
      'survey.administrativeLocation': 'ທີ່ຢູ່ປົກຄອງ',
      'survey.landUse': 'ການນຳໃຊ້ທີ່ດິນ',
      'survey.landCondition': 'ສະພາບທີ່ດິນ',
      'survey.clearingStatus': 'ສະຖານະການຖາງ',
      'survey.readinessStatus': 'ຄວາມພ້ອມ',
      'survey.crop': 'ພືດປູກ',
      'survey.cropCondition': 'ສະພາບພືດ',
      'survey.quantityUnit': 'ຈຳນວນ ແລະ ຫົວໜ່ວຍ',
      'survey.record': 'ການສຳຫຼວດທີ່ດິນ',
      'survey.surveyor': 'ຜູ້ສຳຫຼວດ',
      'survey.attachment': 'ໄຟລ໌ແນບ',
      'survey.validation.invalid': 'ຂໍ້ມູນສຳຫຼວດບໍ່ຖືກຕ້ອງ.',
      'survey.persistence.failed': 'ບໍ່ສາມາດບັນທຶກຂໍ້ມູນສຳຫຼວດ.',
      'common.all': 'ທັງໝົດ',
      'common.active': 'ໃຊ້ງານ',
      'common.inactive': 'ບໍ່ໃຊ້ງານ',
      'common.edit': 'ແກ້ໄຂ',
      'common.remove': 'ລຶບ',
      'common.confirm': 'ຢືນຢັນ',
      'parcel.list.title': 'ລາຍການແປງດິນ',
      'parcel.list.empty': 'ຍັງບໍ່ມີແປງດິນ.',
      'parcel.list.error': 'ບໍ່ສາມາດໂຫຼດລາຍການແປງດິນ.',
      'parcel.detail.error': 'ບໍ່ສາມາດໂຫຼດລາຍລະອຽດແປງດິນ.',
      'parcel.search': 'ຄົ້ນຫາແປງດິນ',
      'parcel.filter.active': 'ສະຖານະ',
      'parcel.filter.verification': 'ການຢືນຢັນ',
      'parcel.create.action': 'ສ້າງແປງດິນ',
      'parcel.create.title': 'ສ້າງຂໍ້ມູນແປງດິນ',
      'parcel.edit.title': 'ແກ້ໄຂແປງດິນ',
      'parcel.code': 'ລະຫັດແປງ',
      'parcel.name': 'ຊື່ແປງດິນ',
      'parcel.section.identity': 'ຂໍ້ມູນແປງດິນ',
      'parcel.section.overview': 'ພາບລວມ',
      'parcel.section.boundary': 'ເຂດແດນ ແລະ ການວັດແທກ',
      'location.country': 'ປະເທດ',
      'location.province': 'ແຂວງ',
      'location.district': 'ເມືອງ',
      'location.village': 'ບ້ານ',
      'household.code': 'ລະຫັດຄົວເຮືອນ',
      'household.head': 'ຫົວໜ້າຄົວເຮືອນ',
      'household.phone': 'ໂທລະສັບ',
      'household.alternativeContact': 'ຕິດຕໍ່ອື່ນ',
      'geometry.areaM2': 'ເນື້ອທີ່ m²',
      'geometry.areaHa': 'ເນື້ອທີ່ ha',
      'geometry.perimeter': 'ຄວາມຍາວຮອບ',
      'geometry.centroid': 'ຈຸດສູນກາງ',
      'geometry.accuracy': 'ຄວາມຊັດເຈນ',
      'geometry.confidence': 'ຄວາມໝັ້ນໃຈ',
      'boundary.source': 'ແຫຼ່ງເຂດແດນ',
      'boundary.version': 'ສະບັບ',
      'boundary.history.title': 'ປະຫວັດເຂດແດນ',
      'boundary.reconciliation.required': 'ເຂດແດນແປງດິນ ແລະ ຂໍ້ມູນແຜນທີ່ບໍ່ກົງກັນ. ຕ້ອງກວດສອບກ່ອນສົ່ງອອກ KML/KMZ.',
      'boundary.reconciliation.eligible': 'ຂໍ້ມູນແຜນທີ່ກົງກັນແລ້ວ. ສາມາດຄືນຄ່າລະຫັດແຜນທີ່ທີ່ຂາດໃຫ້ແປງດິນເກົ່າ.',
      'boundary.reconciliation.action': 'ຄືນຄ່າລະຫັດແຜນທີ່',
      'boundary.reconciliation.confirm': 'ຄືນຄ່າລະຫັດທີ່ຂາດໃຫ້ແປງນີ້ ເມື່ອກວດຂໍ້ມູນແລ້ວວ່າກົງກັນ. ສືບຕໍ່ບໍ?',
      'boundary.reconciliation.success': 'ຄືນຄ່າລະຫັດແຜນທີ່ໃຫ້ແປງດິນແລ້ວ.',
      'boundary.reconciliation.manual': 'ຂໍ້ມູນປ່ຽນໄປ ຫຼື ຍັງບໍ່ກົງກັນ. ຕ້ອງກວດສອບດ້ວຍມື.',
      'boundary.audit.visibleSummary': 'ສະຖານະເຂດແດນຂອງແປງທີ່ສະແດງ',
      'boundary.audit.filter': 'ກັ່ນຕອງຕາມສະຖານະເຂດແດນ',
      'boundary.audit.unlinked': 'ຍັງບໍ່ເຊື່ອມຂໍ້ມູນແຜນທີ່',
      'boundary.audit.consistent': 'ຂໍ້ມູນກົງກັນ',
      'boundary.audit.repairableLegacyIdentity': 'ສາມາດຄືນຄ່າລະຫັດ',
      'boundary.audit.needsReconciliation': 'ຕ້ອງກວດສອບດ້ວຍມື',
      'boundary.issue.missingLink': 'ບໍ່ມີການເຊື່ອມກັບຂໍ້ມູນແຜນທີ່.',
      'boundary.issue.identityMismatch': 'ລະຫັດແຜນທີ່ຂອງແປງ ແລະ ຂໍ້ມູນເຊື່ອມບໍ່ກົງກັນ.',
      'boundary.issue.missingFeature': 'ບໍ່ພົບລາຍການແຜນທີ່ທີ່ເຊື່ອມໄວ້.',
      'boundary.issue.wrongFeatureType': 'ລາຍການແຜນທີ່ທີ່ເຊື່ອມບໍ່ແມ່ນແປງດິນ.',
      'boundary.issue.missingRevision': 'ບໍ່ພົບສະບັບແຜນທີ່ປັດຈຸບັນ.',
      'boundary.issue.invalidGeometry': 'ຂາດຮູບຊົງຫຼາຍຫຼ່ຽມໃນລາຍການ ຫຼື ສະບັບ.',
      'boundary.issue.missingBoundaryVersion': 'ບໍ່ພົບສະບັບເຂດແດນປັດຈຸບັນທີ່ຖືກຕ້ອງ.',
      'boundary.issue.boundaryReferenceMismatch': 'ສະບັບແຜນທີ່ອ້າງອີງປະຫວັດເຂດແດນບໍ່ກົງກັນ.',
      'boundary.issue.boundaryGeometryMismatch': 'ຮູບຊົງເຂດແດນຂອງແປງ ແລະ ແຜນທີ່ບໍ່ກົງກັນ.',
      'boundary.source.gps': 'GPS',
      'boundary.source.googleEarth': 'Google Earth',
      'boundary.source.manual': 'ກຳນົດເອງ',
      'boundary.source.cad': 'CAD',
      'boundary.source.imported': 'ນຳເຂົ້າ',
      'verification.draft': 'ຮ່າງ',
      'verification.measured': 'ວັດແທກແລ້ວ',
      'verification.verified': 'ຢືນຢັນແລ້ວ',
      'verification.rejected': 'ຖືກປະຕິເສດ',
      'verification.confirm.title': 'ປ່ຽນເຂດແດນທີ່ຢືນຢັນແລ້ວ?',
      'crop.empty': 'ຍັງບໍ່ມີພືດ.',
      'crop.add': 'ເພີ່ມພືດ',
      'crop.edit': 'ແກ້ໄຂພືດ',
      'crop.type': 'ຊະນິດພືດ',
      'crop.quantity': 'ຈຳນວນ',
      'crop.unit': 'ຫົວໜ່ວຍ',
      'crop.condition.unknown': 'ບໍ່ຮູ້',
      'crop.condition.planned': 'ວາງແຜນ',
      'crop.condition.growing': 'ກຳລັງເຕີບໂຕ',
      'crop.condition.healthy': 'ດີ',
      'crop.condition.stressed': 'ບໍ່ແຂງແຮງ',
      'crop.condition.harvested': 'ເກັບກ່ຽວແລ້ວ',
      'survey.empty': 'ຍັງບໍ່ມີການສຳຫຼວດ.',
      'attachment.empty': 'ຍັງບໍ່ມີໄຟລ໌ແນບ.',
      'googleEarth.title': 'Google Earth',
      'googleEarth.import': 'ນຳເຂົ້າ KML/KMZ',
      'googleEarth.exportKml': 'ສົ່ງອອກ KML',
      'googleEarth.exportKmz': 'ສົ່ງອອກ KMZ',
      'googleEarth.open': 'ເປີດດ້ວຍ Google Earth',
      'googleEarth.openSuccess': 'ເປີດໄຟລ໌ເຂດແດນແລ້ວ.',
      'googleEarth.openUnavailable': 'ບໍ່ພົບແອັບທີ່ສາມາດເປີດໄຟລ໌ນີ້.',
      'gps.preview.title': 'ຕົວຢ່າງການວັດ GPS',
      'gps.start': 'ວັດແທກ GPS',
      'gps.confirm': 'ນຳໃຊ້ເຂດແດນ GPS',
      'import.preview.title': 'ຕົວຢ່າງກ່ອນນຳເຂົ້າ',
      'import.warning.missingAgricoMetadata': 'ໄຟລ໌ບໍ່ມີ metadata AGRICO.',
      'validation.required': 'ຈຳເປັນຕ້ອງປ້ອນຂໍ້ມູນນີ້.',
      'attachment.addMetadata': 'ເພີ່ມຮູບ / ເອກະສານ',
      'landUse.agricultural': 'ກະສິກຳ',
      'landUse.residential': 'ທີ່ຢູ່ອາໄສ',
      'landUse.forest': 'ປ່າໄມ້',
      'landUse.pasture': 'ທົ່ງຫຍ້າ',
      'landUse.mixed': 'ປະສົມ',
      'landUse.other': 'ອື່ນໆ',
      'landCondition.unknown': 'ບໍ່ຮູ້',
      'landCondition.unused': 'ຍັງບໍ່ໃຊ້',
      'landCondition.cultivated': 'ກຳລັງປູກຝັງ',
      'landCondition.degraded': 'ເສື່ອມໂຊມ',
      'landCondition.flooded': 'ນ້ຳຖ້ວມ',
      'landCondition.other': 'ອື່ນໆ',
      'clearing.unknown': 'ບໍ່ຮູ້',
      'clearing.notRequired': 'ບໍ່ຈຳເປັນ',
      'clearing.notStarted': 'ຍັງບໍ່ຖາງ',
      'clearing.partial': 'ບາງສ່ວນ',
      'clearing.completed': 'ສຳເລັດ',
      'readiness.unknown': 'ບໍ່ຮູ້',
      'readiness.notReady': 'ຍັງບໍ່ພ້ອມ',
      'readiness.preparation': 'ກຳລັງກຽມ',
      'readiness.ready': 'ພ້ອມ',
    },
    'en': {
      ..._shellEn,
      'app.name': 'AGRICO ERP',
      'app.tagline': 'Smart agriculture management',
      'auth.username': 'Email / Username',
      'auth.password': 'Password',
      'auth.forgotPassword': 'Forgot password?',
      'auth.signIn': 'SIGN IN',
      'auth.demoHint': '💡 (Tap to enter the demo without a password)',
      'common.loading': 'Loading…',
      'common.retry': 'Retry',
      'common.cancel': 'Cancel',
      'common.save': 'Save',
      'error.unauthorized': 'You do not have permission for this action.',
      'error.permissionDenied': 'You do not have permission for this action.',
      'landParcel.create.success': 'Land parcel created.',
      'landParcel.update.success': 'Land parcel details updated.',
      'landParcel.error.notFound': 'Land parcel not found.',
      'landParcel.geometry.invalid': 'The land parcel boundary is invalid.',
      'landParcel.persistence.failed':
          'The land parcel change could not be saved.',
      'landParcel.boundary.verifiedConfirmation':
          'This boundary is verified. Confirm before replacing it.',
      'landParcel.boundary.replaceSuccess': 'Land parcel boundary updated.',
      'landParcel.boundary.verifySuccess': 'Verification status updated.',
      'boundary.verify.action': 'Verify boundary',
      'boundary.verify.confirmTitle': 'Verify boundary?',
      'boundary.verify.confirmMessage':
          'After verification, replacing this boundary will require explicit confirmation.',
      'landParcel.gps.invalidSource': 'The GPS measurement source is invalid.',
      'landParcel.import.previewReady': 'Import preview is ready.',
      'landParcel.import.failed': 'The KML/KMZ file could not be read.',
      'landParcel.export.success': 'KML/KMZ export is ready.',
      'landParcel.export.failed': 'The KML/KMZ file could not be exported.',
      'landParcel.preview.warning': 'Review warnings before confirming.',
      'survey.household': 'Household',
      'survey.administrativeLocation': 'Administrative location',
      'survey.landUse': 'Land use',
      'survey.landCondition': 'Land condition',
      'survey.clearingStatus': 'Clearing status',
      'survey.readinessStatus': 'Readiness status',
      'survey.crop': 'Crop',
      'survey.cropCondition': 'Crop condition',
      'survey.quantityUnit': 'Quantity and unit',
      'survey.record': 'Land survey',
      'survey.surveyor': 'Surveyor',
      'survey.attachment': 'Attachment',
      'survey.validation.invalid': 'The survey data is invalid.',
      'survey.persistence.failed': 'The survey data could not be saved.',
      'common.all': 'All',
      'common.active': 'Active',
      'common.inactive': 'Inactive',
      'common.edit': 'Edit',
      'common.remove': 'Remove',
      'common.confirm': 'Confirm',
      'parcel.list.title': 'Land parcels',
      'parcel.list.empty': 'No land parcels yet.',
      'parcel.list.error': 'Land parcels could not be loaded.',
      'parcel.detail.error': 'Land parcel details could not be loaded.',
      'parcel.search': 'Search parcels',
      'parcel.filter.active': 'Status',
      'parcel.filter.verification': 'Verification',
      'parcel.create.action': 'Create parcel',
      'parcel.create.title': 'Create land parcel',
      'parcel.edit.title': 'Edit land parcel',
      'parcel.code': 'Parcel code',
      'parcel.name': 'Parcel name',
      'parcel.section.identity': 'Parcel information',
      'parcel.section.overview': 'Overview',
      'parcel.section.boundary': 'Boundary and measurement',
      'location.country': 'Country',
      'location.province': 'Province',
      'location.district': 'District',
      'location.village': 'Village / Ban',
      'household.code': 'Household code',
      'household.head': 'Head of household',
      'household.phone': 'Phone',
      'household.alternativeContact': 'Alternative contact',
      'geometry.areaM2': 'Area m²',
      'geometry.areaHa': 'Area ha',
      'geometry.perimeter': 'Perimeter',
      'geometry.centroid': 'Centroid',
      'geometry.accuracy': 'Accuracy',
      'geometry.confidence': 'Confidence',
      'boundary.source': 'Boundary source',
      'boundary.version': 'Version',
      'boundary.history.title': 'Boundary history',
      'boundary.reconciliation.required': 'Parcel boundary and spatial data disagree. Reconcile them before exporting KML/KMZ.',
      'boundary.reconciliation.eligible': 'Spatial data matches. The missing spatial ID on this legacy parcel can be restored.',
      'boundary.reconciliation.action': 'Restore spatial ID',
      'boundary.reconciliation.confirm': 'Restore only this parcel’s missing spatial ID if the data still matches. Continue?',
      'boundary.reconciliation.success': 'The parcel’s spatial ID has been restored.',
      'boundary.reconciliation.manual': 'The data changed or does not match. Manual reconciliation is required.',
      'boundary.audit.visibleSummary': 'Boundary status of visible parcels',
      'boundary.audit.filter': 'Filter by boundary status',
      'boundary.audit.unlinked': 'Not linked to spatial data',
      'boundary.audit.consistent': 'Synchronized',
      'boundary.audit.repairableLegacyIdentity': 'Spatial ID can be restored',
      'boundary.audit.needsReconciliation': 'Manual reconciliation needed',
      'boundary.issue.missingLink': 'The spatial link is missing.',
      'boundary.issue.identityMismatch': 'The parcel and link have different spatial IDs.',
      'boundary.issue.missingFeature': 'The linked spatial feature is missing.',
      'boundary.issue.wrongFeatureType': 'The linked spatial feature is not a parcel.',
      'boundary.issue.missingRevision': 'The current spatial revision is missing.',
      'boundary.issue.invalidGeometry': 'Polygon geometry is missing from the feature or revision.',
      'boundary.issue.missingBoundaryVersion': 'The current boundary history version is missing or duplicated.',
      'boundary.issue.boundaryReferenceMismatch': 'The spatial revision references another boundary history entry.',
      'boundary.issue.boundaryGeometryMismatch': 'The parcel and spatial polygon boundaries differ.',
      'boundary.source.gps': 'GPS',
      'boundary.source.googleEarth': 'Google Earth',
      'boundary.source.manual': 'Manual',
      'boundary.source.cad': 'CAD',
      'boundary.source.imported': 'Imported',
      'verification.draft': 'Draft',
      'verification.measured': 'Measured',
      'verification.verified': 'Verified',
      'verification.rejected': 'Rejected',
      'verification.confirm.title': 'Replace verified boundary?',
      'crop.empty': 'No crops.',
      'crop.add': 'Add crop',
      'crop.edit': 'Edit crop',
      'crop.type': 'Crop type',
      'crop.quantity': 'Quantity',
      'crop.unit': 'Unit',
      'crop.condition.unknown': 'Unknown',
      'crop.condition.planned': 'Planned',
      'crop.condition.growing': 'Growing',
      'crop.condition.healthy': 'Healthy',
      'crop.condition.stressed': 'Stressed',
      'crop.condition.harvested': 'Harvested',
      'survey.empty': 'No surveys.',
      'attachment.empty': 'No attachments.',
      'googleEarth.title': 'Google Earth',
      'googleEarth.import': 'Import KML/KMZ',
      'googleEarth.exportKml': 'Export KML',
      'googleEarth.exportKmz': 'Export KMZ',
      'googleEarth.open': 'Open in Google Earth',
      'googleEarth.openSuccess': 'Boundary file opened.',
      'googleEarth.openUnavailable':
          'No compatible app is available to open this file.',
      'gps.preview.title': 'GPS measurement preview',
      'gps.start': 'Measure with GPS',
      'gps.confirm': 'Apply GPS boundary',
      'import.preview.title': 'Import preview',
      'import.warning.missingAgricoMetadata':
          'This file has no AGRICO metadata.',
      'validation.required': 'This field is required.',
      'attachment.addMetadata': 'Add photo / document',
      'landUse.agricultural': 'Agricultural',
      'landUse.residential': 'Residential',
      'landUse.forest': 'Forest',
      'landUse.pasture': 'Pasture',
      'landUse.mixed': 'Mixed',
      'landUse.other': 'Other',
      'landCondition.unknown': 'Unknown',
      'landCondition.unused': 'Unused',
      'landCondition.cultivated': 'Cultivated',
      'landCondition.degraded': 'Degraded',
      'landCondition.flooded': 'Flooded',
      'landCondition.other': 'Other',
      'clearing.unknown': 'Unknown',
      'clearing.notRequired': 'Not required',
      'clearing.notStarted': 'Not started',
      'clearing.partial': 'Partial',
      'clearing.completed': 'Completed',
      'readiness.unknown': 'Unknown',
      'readiness.notReady': 'Not ready',
      'readiness.preparation': 'Preparation',
      'readiness.ready': 'Ready',
    },
  };

  String text(String key) {
    final languageCode = _catalogue.containsKey(locale.languageCode)
        ? locale.languageCode
        : 'vi';
    return _catalogue[languageCode]?[key] ?? _catalogue['vi']?[key] ?? key;
  }

  @visibleForTesting
  static Set<String> keysFor(Locale locale) =>
      _catalogue[locale.languageCode]?.keys.toSet() ?? const {};
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => AppLocalizations.supportedLocales.any(
    (supported) => supported.languageCode == locale.languageCode,
  );

  @override
  Future<AppLocalizations> load(Locale locale) =>
      SynchronousFuture(AppLocalizations(locale));

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

extension AppLocalizationsContext on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}
