import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

/// Lightweight localization facade used while legacy screens are migrated.
///
/// Keeping the catalogue in Dart makes the v2 foundation immediately usable
/// without coupling domain code to Flutter's generated localization classes.
class AppLocalizations {
  const AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = <Locale>[
    Locale('vi'),
    Locale('lo'),
    Locale('en'),
  ];

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    final value = Localizations.of<AppLocalizations>(context, AppLocalizations);
    assert(value != null, 'AppLocalizations is not registered in MaterialApp.');
    return value!;
  }

  static const _shellVi = <String, String>{
    'nav.home': 'Trang chủ',
    'nav.modules': 'Phân hệ',
    'nav.create': 'Thêm mới',
    'nav.reports': 'Báo cáo',
    'nav.profile': 'Cá nhân',
    'home.greeting': 'Xin chào',
    'home.farmUnavailable': 'Chưa chọn trang trại',
    'home.kpi': 'Chỉ số chính',
    'home.quickActions': 'Truy cập nhanh',
    'home.farmOverview': 'Tổng quan trang trại',
    'home.recentActivity': 'Hoạt động gần đây',
    'kpi.parcels': 'Lô đất',
    'kpi.seasons': 'Mùa vụ',
    'kpi.tasks': 'Công việc',
    'kpi.alerts': 'Cảnh báo',
    'modules.title': 'Phân hệ',
    'modules.production': 'Sản xuất & đồng ruộng',
    'modules.resources': 'Nguồn lực',
    'modules.finance': 'Tài chính & chi phí',
    'modules.support': 'Quản lý & hỗ trợ',
    'module.parcels': 'Lô đất',
    'module.households': 'Hộ gia đình',
    'work.title': 'Công việc trên lô đất',
    'work.addResource': 'Thêm máy hoặc nhân công',
    'work.addEvent': 'Ghi công việc',
    'work.machine': 'Máy móc',
    'work.worker': 'Nhân công',
    'work.clearing': 'Khai hoang',
    'work.cultivation': 'Canh tác',
    'work.code': 'Mã nguồn lực',
    'work.name': 'Tên máy hoặc nhân công',
    'work.description': 'Nội dung công việc',
    'work.areaM2': 'Diện tích thực hiện (m²)',
    'work.empty': 'Chưa có công việc trên lô đất.',
    'work.loadFailed': 'Không thể tải công việc.',
    'work.saveFailed': 'Không thể lưu. Kiểm tra thông tin và nguồn lực.',
    'timeline.title': 'Hiện trạng và phân mảnh',
    'timeline.capture': 'Ghi hiện trạng',
    'timeline.link': 'Liên kết lô nguồn',
    'timeline.beforeClearing': 'Trước khai hoang',
    'timeline.afterClearing': 'Sau khai hoang',
    'timeline.cultivation': 'Canh tác',
    'timeline.subdivision': 'Phân mảnh',
    'timeline.merge': 'Gộp lô',
    'timeline.partialDerivation': 'Chuyển một phần',
    'timeline.areaM2': 'Diện tích chuyển (m²)',
    'timeline.empty': 'Chưa ghi hiện trạng hoặc liên kết lô.',
    'timeline.loadFailed': 'Không thể tải lịch sử đất.',
    'timeline.saveFailed': 'Không thể lưu hiện trạng hoặc liên kết lô.',
    'subdivision.title': 'Tách lô theo ranh giới',
    'subdivision.enclosedMode': 'Lô bên trong',
    'subdivision.edgeMode': 'Lô sát biên ngoài',
    'subdivision.instruction': 'Chạm từng góc của mảnh đất như trên Google Earth. Các mảnh được đo riêng; cạnh chồng nhau hoặc hơi vượt biên lô lớn vẫn được chấp nhận. Chạm lại điểm đầu hoặc bấm Khép kín và xem trước.',
    'subdivision.reset': 'Vẽ lại đường cắt',
    'subdivision.fragment': 'Lô',
    'subdivision.editSelected': 'Vẽ từng mảnh trong vùng đất lớn:',
    'subdivision.overview': 'Tổng thể các lô:',
    'subdivision.undoPoint': 'Bỏ điểm vừa chạm',
    'subdivision.autoFinish': 'Chọn ít nhất 3 góc, rồi chạm điểm đầu hoặc bấm Khép kín và xem trước.',
    'subdivision.closeOutline': 'Khép kín và xem trước',
    'subdivision.distinctEnd': 'Cần có điểm biên thứ hai khác điểm đầu trước khi khép kín.',
    'subdivision.closedBoundary': 'Các lô được tự động khép kín theo ranh giới nguồn; không có khe hở giữa các lô.',
    'subdivision.resetAll': 'Vẽ lại tất cả đường cắt',
    'subdivision.invalidCut': 'Chưa khép kín được đa giác này. Cần ít nhất ba góc và đường không tự cắt.',
    'subdivision.preview': 'Số lô và diện tích từng lô',
    'subdivision.locationRequired': 'Địa bàn của lô chưa khớp danh mục; hãy đối soát trước khi tách.',
    'subdivision.firstName': 'Tên lô thứ nhất',
    'subdivision.secondName': 'Tên lô thứ hai',
    'subdivision.save': 'Lưu tất cả lô mới',
    'subdivision.loadFailed': 'Không thể tải lô nguồn.',
    'subdivision.saveFailed': 'Không thể tách lô. Kiểm tra ranh giới, địa bàn và tên lô.',
    'household.directory': 'Danh sách hộ',
    'household.detail': 'Thông tin hộ',
    'household.add': 'Thêm hộ',
    'household.edit': 'Sửa thông tin hộ',
    'household.editScope': 'Mã hộ và địa bàn không đổi. Tên chủ hộ đã lưu trên các thửa cũ được giữ nguyên.',
    'household.codeAutomatic': 'Mã hộ H00001… sẽ được cấp tự động khi lưu. Chọn bản từ danh mục địa bàn.',
    'household.noVillages': 'Chưa có bản hợp lệ trong danh mục địa bàn.',
    'household.saveFailed': 'Không thể lưu hộ. Kiểm tra thông tin và thử lại.',
    'household.parcels': 'Các thửa của hộ',
    'household.noParcels': 'Hộ chưa liên kết thửa nào.',
    'household.notFound': 'Không tìm thấy hộ trong trang trại này.',
    'household.search': 'Tìm theo mã hộ, tên hoặc bản',
    'household.empty': 'Chưa có hộ nào.',
    'household.noMatches': 'Không tìm thấy hộ phù hợp.',
    'household.loadFailed': 'Không thể tải danh sách hộ.',
    'module.seasons': 'Mùa vụ',
    'module.productionLogs': 'Nhật ký sản xuất',
    'module.harvest': 'Thu hoạch',
    'module.employees': 'Nhân sự',
    'module.machines': 'Máy móc',
    'module.warehouse': 'Kho vật tư',
    'module.fuel': 'Nhiên liệu',
    'module.costs': 'Chi phí sản xuất',
    'module.finance': 'Tài chính',
    'finance.receipt': 'Thu',
    'finance.payment': 'Chi',
    'finance.add': 'Thêm chứng từ',
    'finance.category': 'Nội dung',
    'finance.amount': 'Số tiền',
    'finance.currency': 'Đơn vị tiền',
    'finance.currency.lak': 'Kíp Lào (LAK)',
    'finance.currency.vnd': 'Đồng Việt Nam (VND)',
    'finance.currency.lak.short': 'kíp',
    'finance.currency.vnd.short': 'đồng',
    'finance.date': 'Ngày chứng từ',
    'finance.invalid': 'Nhập nội dung và số tiền nguyên lớn hơn 0.',
    'finance.saveFailed': 'Không thể lưu chứng từ.',
    'module.resources': 'Máy móc & nhân sự',
    'module.tasks': 'Công việc',
    'module.ai': 'AI trợ lý',
    'module.cloud': 'Đồng bộ Cloud',
    'module.backup': 'Sao lưu cục bộ',
    'backup.title': 'Sao lưu dữ liệu',
    'backup.explanation': 'Xuất hai cơ sở dữ liệu, ảnh và tệp cục bộ thành bản sao được mã hóa bằng mật khẩu. Giữ tệp ngoài điện thoại.',
    'backup.externalFiles': 'Nếu tệp cục bộ bị thiếu, xuất sao lưu sẽ thất bại. Bản sao cũ dạng JSON chưa được mã hóa.',
    'backup.newPasswordTitle': 'Đặt mật khẩu sao lưu',
    'backup.passwordTitle': 'Mật khẩu bản sao lưu',
    'backup.password': 'Mật khẩu',
    'backup.confirmPassword': 'Nhập lại mật khẩu',
    'backup.passwordAdvice': 'Ít nhất 12 ký tự. Hãy lưu mật khẩu an toàn; mất mật khẩu sẽ không mở được tệp.',
    'backup.passwordInvalid': 'Mật khẩu không đúng hoặc tệp mã hóa bị hỏng.',
    'backup.legacyTitle': 'Cảnh báo: tệp chưa mã hóa',
    'backup.legacyUnencrypted': 'Bản sao cũ chưa mã hóa. Ai có tệp đều có thể đọc dữ liệu.',
    'backup.export': 'Xuất bản sao',
    'backup.inspect': 'Kiểm tra tệp sao lưu',
    'backup.preflight': 'Thử khôi phục (không ghi dữ liệu)',
    'backup.preflightValid': 'Thử khôi phục đạt. Dữ liệu hiện tại không thay đổi. Số bản ghi theo bảng:',
    'backup.preflightFailed': 'Chưa thể khôi phục: tệp thiếu dữ liệu, cấu trúc không khớp hoặc kiểm tra quan hệ thất bại.',
    'backup.preflight.missingCosts': 'Tệp sao lưu cũ chưa có cơ sở dữ liệu chi phí. Hãy xuất một tệp mới rồi thử lại.',
    'backup.preflight.schemaVersion': 'Phiên bản cơ sở dữ liệu trong tệp khác với ứng dụng hiện tại.',
    'backup.preflight.tables': 'Danh sách bảng trong tệp khác với ứng dụng hiện tại.',
    'backup.preflight.sqlite': 'Không dựng được dữ liệu sao lưu trong SQLite tạm.',
    'backup.preflight.integrity': 'Kiểm tra tính toàn vẹn của SQLite tạm thất bại.',
    'backup.preflight.foreignKeys': 'Dữ liệu có tham chiếu khóa ngoại không hợp lệ.',
    'backup.apply': 'Khôi phục khi mở lại ứng dụng',
    'backup.applyTitle': 'Xác nhận thay dữ liệu trên máy',
    'backup.applyWarning': 'Lần mở ứng dụng tiếp theo sẽ thay dữ liệu trong cả hai cơ sở dữ liệu bằng tệp đã chọn. Các thay đổi sau thời điểm sao lưu sẽ mất. Chỉ tệp cục bộ được đóng gói trong bản sao v3 mới được khôi phục. Hãy giữ một bản sao lưu riêng trước khi tiếp tục.',
    'backup.applyConfirm': 'Xác nhận khôi phục',
    'backup.scheduled': 'Đã chuẩn bị. Đóng hẳn ứng dụng rồi mở lại để áp dụng.',
    'backup.applied': 'Đã khôi phục hai cơ sở dữ liệu. Kiểm tra lại các bản ghi của bạn.',
    'backup.previous': 'Xem dữ liệu trước lần khôi phục',
    'backup.applyFailed': 'Khôi phục không thành công. Giao dịch đã được hoàn tác; kiểm tra lại dữ liệu hiện tại.',
    'backup.valid': 'Tệp hợp lệ. Số bản ghi theo bảng:',
    'backup.invalid': 'Tệp sao lưu hỏng hoặc không đúng định dạng.',
    'backup.exportFailed': 'Không thể xuất bản sao.',
    'module.administrativeCatalog': 'Danh mục địa bàn',
    'admin.title': 'Danh mục địa bàn',
    'admin.add': 'Thêm địa bàn',
    'admin.level': 'Cấp hành chính',
    'admin.parent': 'Thuộc địa bàn',
    'admin.name': 'Tên địa bàn',
    'admin.code': 'Mã nội bộ',
    'admin.alternate': 'Tên khác (tùy chọn)',
    'admin.province': 'Tỉnh',
    'admin.district': 'Huyện',
    'admin.village': 'Bản',
    'admin.country': 'Quốc gia',
    'admin.root': 'Gốc',
    'admin.parentRequired': 'Cần chọn địa bàn cấp trên.',
    'admin.saveFailed': 'Không thể lưu. Kiểm tra tên, mã và mã trùng trong cùng địa bàn cấp trên.',
    'admin.loadFailed': 'Không thể tải danh mục địa bàn.',
    'admin.internalCodes': 'Mã quản trị nội bộ AGRICO; mã đã cấp được giữ nguyên.',
    'quickCreate.logs': 'Nhật ký',
    'quickCreate.harvest': 'Thu hoạch',
    'quickCreate.costs': 'Chi phí',
    'quickCreate.employees': 'Nhân sự',
    'quickCreate.machines': 'Máy móc',
    'quickCreate.tasks': 'Công việc',
    'quickCreate.other': 'Khác',
    'profile.title': 'Cá nhân',
    'profile.language': 'Ngôn ngữ',
    'profile.settings': 'Cài đặt',
    'common.unavailable': 'Chưa khả dụng',
    'common.empty': 'Chưa có dữ liệu',
    'common.open': 'Mở',
    'startup.error': 'Không thể khởi động AGRICO.',
    'parcel.boundaryRequired':
        'Hãy đo GPS hoặc nhập KML/KMZ trước khi tạo lô đất.',
    'export.unavailable': 'Không thể lưu hoặc mở tệp xuất.',
    'gps.permissionDenied': 'Quyền vị trí bị từ chối.',
  };
  static const _shellLo = <String, String>{
    'nav.home': 'ໜ້າຫຼັກ',
    'nav.modules': 'ໂມດູນ',
    'nav.create': 'ເພີ່ມໃໝ່',
    'nav.reports': 'ລາຍງານ',
    'nav.profile': 'ສ່ວນຕົວ',
    'home.greeting': 'ສະບາຍດີ',
    'home.farmUnavailable': 'ຍັງບໍ່ໄດ້ເລືອກຟາມ',
    'home.kpi': 'ຕົວຊີ້ວັດຫຼັກ',
    'home.quickActions': 'ເຂົ້າເຖິງດ່ວນ',
    'home.farmOverview': 'ພາບລວມຟາມ',
    'home.recentActivity': 'ກິດຈະກຳຫຼ້າສຸດ',
    'kpi.parcels': 'ແປງດິນ',
    'kpi.seasons': 'ລະດູການ',
    'kpi.tasks': 'ວຽກ',
    'kpi.alerts': 'ແຈ້ງເຕືອນ',
    'modules.title': 'ໂມດູນ',
    'modules.production': 'ການຜະລິດ ແລະ ພາກສະໜາມ',
    'modules.resources': 'ຊັບພະຍາກອນ',
    'modules.finance': 'ການເງິນ ແລະ ຕົ້ນທຶນ',
    'modules.support': 'ການຈັດການ ແລະ ຊ່ວຍເຫຼືອ',
    'module.parcels': 'ແປງດິນ',
    'module.households': 'ຄອບຄົວ',
    'work.title': 'ວຽກງານໃນແປງດິນ',
    'work.addResource': 'ເພີ່ມເຄື່ອງຈັກ ຫຼື ແຮງງານ',
    'work.addEvent': 'ບັນທຶກວຽກ',
    'work.machine': 'ເຄື່ອງຈັກ',
    'work.worker': 'ແຮງງານ',
    'work.clearing': 'ຖາງປ່າ',
    'work.cultivation': 'ປູກຝັງ',
    'work.code': 'ລະຫັດຊັບພະຍາກອນ',
    'work.name': 'ຊື່ເຄື່ອງຈັກ ຫຼື ແຮງງານ',
    'work.description': 'ລາຍລະອຽດວຽກ',
    'work.areaM2': 'ເນື້ອທີ່ປະຕິບັດ (m²)',
    'work.empty': 'ຍັງບໍ່ມີວຽກໃນແປງດິນ.',
    'work.loadFailed': 'ໂຫຼດວຽກບໍ່ໄດ້.',
    'work.saveFailed': 'ບັນທຶກບໍ່ໄດ້. ກວດຂໍ້ມູນ ແລະ ຊັບພະຍາກອນ.',
    'timeline.title': 'ສະພາບດິນ ແລະ ການແບ່ງແປງ',
    'timeline.capture': 'ບັນທຶກສະພາບດິນ',
    'timeline.link': 'ເຊື່ອມໂຍງແປງຕົ້ນທາງ',
    'timeline.beforeClearing': 'ກ່ອນຖາງປ່າ',
    'timeline.afterClearing': 'ຫຼັງຖາງປ່າ',
    'timeline.cultivation': 'ປູກຝັງ',
    'timeline.subdivision': 'ແບ່ງແປງ',
    'timeline.merge': 'ລວມແປງ',
    'timeline.partialDerivation': 'ໂອນບາງສ່ວນ',
    'timeline.areaM2': 'ເນື້ອທີ່ໂອນ (m²)',
    'timeline.empty': 'ຍັງບໍ່ມີປະຫວັດສະພາບດິນ.',
    'timeline.loadFailed': 'ໂຫຼດປະຫວັດດິນບໍ່ໄດ້.',
    'timeline.saveFailed': 'ບັນທຶກສະພາບ ຫຼື ເຊື່ອມແປງບໍ່ໄດ້.',
    'subdivision.title': 'ແບ່ງແປງຕາມເຂດແດນ',
    'subdivision.enclosedMode': 'ແປງຂ້າງໃນ',
    'subdivision.edgeMode': 'ແປງຕິດຂອບນອກ',
    'subdivision.instruction': 'ແຕະມຸມຂອງແປງແຕ່ລະແປງຄື Google Earth. ແປງທີ່ຂອບທັບກັນ ຫຼື ເກີນຂອບໃຫຍ່ເລັກນ້ອຍ ຍັງສາມາດວັດໄດ້. ກົດປິດຮູບເມື່ອແຕ້ມແລ້ວ.',
    'subdivision.reset': 'ແຕ້ມເສັ້ນຕັດໃໝ່',
    'subdivision.fragment': 'ແປງ',
    'subdivision.editSelected': 'ແຕ້ມແປງນ້ອຍແຕ່ລະແປງໃນເຂດໃຫຍ່:',
    'subdivision.overview': 'ພາບລວມແປງ:',
    'subdivision.undoPoint': 'ລຶບຈຸດຫຼ້າສຸດ',
    'subdivision.autoFinish': 'ເລືອກຢ່າງໜ້ອຍ 3 ມຸມ ແລ້ວກົດປິດຮູບ.',
    'subdivision.closeOutline': 'ປິດຮູບ ແລະ ເບິ່ງກ່ອນ',
    'subdivision.distinctEnd': 'ຕ້ອງມີຈຸດຂອບທີສອງທີ່ຕ່າງຈາກຈຸດຕົ້ນ.',
    'subdivision.closedBoundary': 'ຂອບແປງໃໝ່ປິດອັດຕະໂນມັດຕາມຂອບແປງເດີມ; ບໍ່ມີຊ່ອງວ່າງ.',
    'subdivision.resetAll': 'ແຕ້ມເສັ້ນຕັດທັງໝົດໃໝ່',
    'subdivision.invalidCut': 'ປິດຮູບຫຼາຍຫຼ່ຽມບໍ່ໄດ້. ຕ້ອງມີຢ່າງໜ້ອຍສາມມຸມ ແລະ ເສັ້ນບໍ່ຕັດກັນເອງ.',
    'subdivision.preview': 'ຈຳນວນ ແລະ ເນື້ອທີ່ແຕ່ລະແປງ',
    'subdivision.locationRequired': 'ເຂດຂອງແປງບໍ່ກົງກັບລາຍການ; ກວດສອບກ່ອນ.',
    'subdivision.firstName': 'ຊື່ແປງທຳອິດ',
    'subdivision.secondName': 'ຊື່ແປງທີສອງ',
    'subdivision.save': 'ບັນທຶກແປງໃໝ່ທັງໝົດ',
    'subdivision.loadFailed': 'ໂຫຼດແປງຕົ້ນທາງບໍ່ໄດ້.',
    'subdivision.saveFailed': 'ແບ່ງແປງບໍ່ໄດ້. ກວດຂອບແດນ ແລະ ຊື່.',
    'household.directory': 'ລາຍຊື່ຄອບຄົວ',
    'household.detail': 'ຂໍ້ມູນຄອບຄົວ',
    'household.add': 'ເພີ່ມຄອບຄົວ',
    'household.edit': 'ແກ້ໄຂຂໍ້ມູນຄອບຄົວ',
    'household.editScope': 'ລະຫັດແລະເຂດປົກຄອງບໍ່ປ່ຽນ. ຊື່ທີ່ບັນທຶກໃນແປງດິນເກົ່າຍັງຄົງເດີມ.',
    'household.codeAutomatic': 'ລະຫັດ H00001… ຈະອອກໃຫ້ອັດຕະໂນມັດເມື່ອບັນທຶກ. ເລືອກບ້ານຈາກລາຍການ.',
    'household.noVillages': 'ຍັງບໍ່ມີບ້ານທີ່ໃຊ້ໄດ້ໃນລາຍການ.',
    'household.saveFailed': 'ບັນທຶກຄອບຄົວບໍ່ໄດ້. ກວດຂໍ້ມູນແລ້ວລອງໃໝ່.',
    'household.parcels': 'ແປງດິນຂອງຄອບຄົວ',
    'household.noParcels': 'ຍັງບໍ່ມີແປງດິນທີ່ເຊື່ອມໂຍງ.',
    'household.notFound': 'ບໍ່ພົບຄອບຄົວໃນຟາມນີ້.',
    'household.search': 'ຄົ້ນຫາດ້ວຍລະຫັດ, ຊື່ ຫຼື ບ້ານ',
    'household.empty': 'ຍັງບໍ່ມີຄອບຄົວ.',
    'household.noMatches': 'ບໍ່ພົບຄອບຄົວທີ່ກົງ.',
    'household.loadFailed': 'ໂຫຼດລາຍຊື່ຄອບຄົວບໍ່ໄດ້.',
    'module.seasons': 'ລະດູການ',
    'module.productionLogs': 'ບັນທຶກການຜະລິດ',
    'module.harvest': 'ເກັບກ່ຽວ',
    'module.employees': 'ພະນັກງານ',
    'module.machines': 'ເຄື່ອງຈັກ',
    'module.warehouse': 'ສາງວັດສະດຸ',
    'module.fuel': 'ນ້ຳມັນ',
    'module.costs': 'ຕົ້ນທຶນການຜະລິດ',
    'module.finance': 'ການເງິນ',
    'finance.receipt': 'ຮັບ',
    'finance.payment': 'ຈ່າຍ',
    'finance.add': 'ເພີ່ມໃບບັນທຶກ',
    'finance.category': 'ລາຍການ',
    'finance.amount': 'ຈຳນວນເງິນ',
    'finance.currency': 'ສະກຸນເງິນ',
    'finance.currency.lak': 'ກີບລາວ (LAK)',
    'finance.currency.vnd': 'ດົງຫວຽດນາມ (VND)',
    'finance.currency.lak.short': 'ກີບ',
    'finance.currency.vnd.short': 'ດົງ',
    'finance.date': 'ວັນທີໃບບັນທຶກ',
    'finance.invalid': 'ກະລຸນາປ້ອນລາຍການ ແລະ ຈຳນວນເງິນທີ່ເປັນຈຳນວນເຕັມບວກ.',
    'finance.saveFailed': 'ບໍ່ສາມາດບັນທຶກໄດ້.',
    'module.resources': 'ເຄື່ອງຈັກ ແລະ ພະນັກງານ',
    'module.tasks': 'ວຽກ',
    'module.ai': 'ຜູ້ຊ່ວຍ AI',
    'module.cloud': 'ຊິງ Cloud',
    'module.backup': 'ສຳຮອງຂໍ້ມູນໃນເຄື່ອງ',
    'backup.title': 'ສຳຮອງຂໍ້ມູນ',
    'backup.explanation': 'ສົ່ງອອກຖານຂໍ້ມູນສອງຖານ ພ້ອມຮູບ ແລະ ໄຟລ໌ໃນເຄື່ອງ ເປັນໄຟລ໌ສຳຮອງທີ່ເຂົ້າລະຫັດດ້ວຍລະຫັດຜ່ານ.',
    'backup.externalFiles': 'ຖ້າໄຟລ໌ໃນເຄື່ອງຫາຍ ການສົ່ງອອກຈະບໍ່ສຳເລັດ. ສຳເນົາ JSON ເກົ່າບໍ່ໄດ້ເຂົ້າລະຫັດ.',
    'backup.newPasswordTitle': 'ຕັ້ງລະຫັດຜ່ານສຳຮອງ',
    'backup.passwordTitle': 'ລະຫັດຜ່ານຂອງໄຟລ໌ສຳຮອງ',
    'backup.password': 'ລະຫັດຜ່ານ',
    'backup.confirmPassword': 'ຢືນຢັນລະຫັດຜ່ານ',
    'backup.passwordAdvice': 'ຢ່າງໜ້ອຍ 12 ຕົວອັກສອນ. ເກັບລະຫັດໃຫ້ປອດໄພ; ຖ້າລືມຈະເປີດໄຟລ໌ບໍ່ໄດ້.',
    'backup.passwordInvalid': 'ລະຫັດຜ່ານບໍ່ຖືກ ຫຼື ໄຟລ໌ເສຍ.',
    'backup.legacyTitle': 'ຄຳເຕືອນ: ໄຟລ໌ບໍ່ໄດ້ເຂົ້າລະຫັດ',
    'backup.legacyUnencrypted': 'ສຳເນົາເກົ່າບໍ່ໄດ້ເຂົ້າລະຫັດ; ຜູ້ທີ່ໄດ້ໄຟລ໌ສາມາດອ່ານໄດ້.',
    'backup.export': 'ສົ່ງອອກ',
    'backup.inspect': 'ກວດໄຟລ໌ສຳຮອງ',
    'backup.preflight': 'ທົດລອງກູ້ຄືນ (ບໍ່ຂຽນຂໍ້ມູນ)',
    'backup.preflightValid': 'ທົດລອງກູ້ຄືນຜ່ານ. ຂໍ້ມູນເກົ່າບໍ່ປ່ຽນ. ຈຳນວນລາຍການ:',
    'backup.preflightFailed': 'ກູ້ຄືນບໍ່ໄດ້: ຂໍ້ມູນຂາດ, ໂຄງສ້າງບໍ່ກົງ ຫຼື ກວດຄວາມສຳພັນບໍ່ຜ່ານ.',
    'backup.preflight.missingCosts': 'ໄຟລ໌ສຳຮອງເກົ່າບໍ່ມີຖານຂໍ້ມູນຄ່າໃຊ້ຈ່າຍ. ກະລຸນາສົ່ງອອກໄຟລ໌ໃໝ່.',
    'backup.preflight.schemaVersion': 'ສະບັບຖານຂໍ້ມູນໃນໄຟລ໌ບໍ່ກົງກັບແອັບ.',
    'backup.preflight.tables': 'ຕາຕະລາງໃນໄຟລ໌ບໍ່ກົງກັບແອັບ.',
    'backup.preflight.sqlite': 'ສ້າງຖານຂໍ້ມູນທົດລອງບໍ່ໄດ້.',
    'backup.preflight.integrity': 'ການກວດຖານຂໍ້ມູນທົດລອງບໍ່ຜ່ານ.',
    'backup.preflight.foreignKeys': 'ຂໍ້ມູນອ້າງອີງບໍ່ຖືກຕ້ອງ.',
    'backup.apply': 'ກູ້ຄືນເມື່ອເປີດແອັບໃໝ່',
    'backup.applyTitle': 'ຢືນຢັນການແທນຂໍ້ມູນ',
    'backup.applyWarning': 'ເມື່ອເປີດແອັບໃໝ່ ຂໍ້ມູນໃນສອງຖານຈະຖືກແທນດ້ວຍໄຟລ໌ນີ້. ການປ່ຽນແປງຫຼັງສຳຮອງຈະຫາຍໄປ. ຈະກູ້ຄືນສະເພາະໄຟລ໌ໃນເຄື່ອງທີ່ຢູ່ໃນສຳເນົາ v3. ກະລຸນາເກັບສຳເນົາອີກຊຸດ.',
    'backup.applyConfirm': 'ຢືນຢັນກູ້ຄືນ',
    'backup.scheduled': 'ກຽມແລ້ວ. ປິດແອັບແລ້ວເປີດໃໝ່.',
    'backup.applied': 'ກູ້ຄືນສອງຖານຂໍ້ມູນແລ້ວ. ກວດລາຍການຂອງທ່ານ.',
    'backup.previous': 'ເບິ່ງຂໍ້ມູນກ່ອນກູ້ຄືນ',
    'backup.applyFailed': 'ກູ້ຄືນບໍ່ສຳເລັດ. ທຸລະກຳຖືກຍົກເລີກ; ກວດຂໍ້ມູນເກົ່າ.',
    'backup.valid': 'ໄຟລ໌ຖືກຕ້ອງ. ຈຳນວນລາຍການ:',
    'backup.invalid': 'ໄຟລ໌ເສຍ ຫຼື ຜິດຮູບແບບ.',
    'backup.exportFailed': 'ສົ່ງອອກບໍ່ໄດ້.',
    'module.administrativeCatalog': 'ລາຍການເຂດປົກຄອງ',
    'admin.title': 'ລາຍການເຂດປົກຄອງ',
    'admin.add': 'ເພີ່ມເຂດ',
    'admin.level': 'ລະດັບ',
    'admin.parent': 'ຂຶ້ນກັບ',
    'admin.name': 'ຊື່ເຂດ',
    'admin.code': 'ລະຫັດພາຍໃນ',
    'admin.alternate': 'ຊື່ອື່ນ (ຖ້າມີ)',
    'admin.province': 'ແຂວງ',
    'admin.district': 'ເມືອງ',
    'admin.village': 'ບ້ານ',
    'admin.country': 'ປະເທດ',
    'admin.root': 'ຮາກ',
    'admin.parentRequired': 'ກະລຸນາເລືອກເຂດແມ່.',
    'admin.saveFailed': 'ບັນທຶກບໍ່ໄດ້: ກວດຊື່ ແລະ ລະຫັດຊ້ຳ.',
    'admin.loadFailed': 'ໂຫຼດລາຍການບໍ່ໄດ້.',
    'admin.internalCodes': 'ລະຫັດພາຍໃນ AGRICO; ລະຫັດເກົ່າບໍ່ປ່ຽນ.',
    'quickCreate.logs': 'ບັນທຶກ',
    'quickCreate.harvest': 'ເກັບກ່ຽວ',
    'quickCreate.costs': 'ຕົ້ນທຶນ',
    'quickCreate.employees': 'ພະນັກງານ',
    'quickCreate.machines': 'ເຄື່ອງຈັກ',
    'quickCreate.tasks': 'ວຽກ',
    'quickCreate.other': 'ອື່ນໆ',
    'profile.title': 'ສ່ວນຕົວ',
    'profile.language': 'ພາສາ',
    'profile.settings': 'ຕັ້ງຄ່າ',
    'common.unavailable': 'ຍັງບໍ່ພ້ອມ',
    'common.empty': 'ຍັງບໍ່ມີຂໍ້ມູນ',
    'common.open': 'ເປີດ',
    'startup.error': 'ບໍ່ສາມາດເລີ່ມ AGRICO.',
    'parcel.boundaryRequired': 'ກະລຸນາວັດ GPS ຫຼື ນຳເຂົ້າ KML/KMZ ກ່ອນ.',
    'export.unavailable': 'ບໍ່ສາມາດບັນທຶກ ຫຼື ເປີດໄຟລ໌.',
    'gps.permissionDenied': 'ສິດທີ່ຕັ້ງຖືກປະຕິເສດ.',
  };
  static const _shellEn = <String, String>{
    'nav.home': 'Home',
    'nav.modules': 'Modules',
    'nav.create': 'Create',
    'nav.reports': 'Reports',
    'nav.profile': 'Profile',
    'home.greeting': 'Welcome',
    'home.farmUnavailable': 'No farm selected',
    'home.kpi': 'Key indicators',
    'home.quickActions': 'Quick actions',
    'home.farmOverview': 'Farm overview',
    'home.recentActivity': 'Recent activity',
    'kpi.parcels': 'Parcels',
    'kpi.seasons': 'Seasons',
    'kpi.tasks': 'Tasks',
    'kpi.alerts': 'Alerts',
    'modules.title': 'Modules',
    'modules.production': 'Production & fields',
    'modules.resources': 'Resources',
    'modules.finance': 'Finance & costs',
    'modules.support': 'Management & support',
    'module.parcels': 'Land parcels',
    'module.households': 'Households',
    'work.title': 'Parcel work',
    'work.addResource': 'Add machine or worker',
    'work.addEvent': 'Record work',
    'work.machine': 'Machine',
    'work.worker': 'Worker',
    'work.clearing': 'Land clearing',
    'work.cultivation': 'Cultivation',
    'work.code': 'Resource code',
    'work.name': 'Machine or worker name',
    'work.description': 'Work description',
    'work.areaM2': 'Worked area (m²)',
    'work.empty': 'No work recorded for this parcel.',
    'work.loadFailed': 'Could not load parcel work.',
    'work.saveFailed': 'Could not save. Check details and resources.',
    'timeline.title': 'Land stages and subdivision',
    'timeline.capture': 'Record land stage',
    'timeline.link': 'Link source parcel',
    'timeline.beforeClearing': 'Before clearing',
    'timeline.afterClearing': 'After clearing',
    'timeline.cultivation': 'Cultivation',
    'timeline.subdivision': 'Subdivision',
    'timeline.merge': 'Merge',
    'timeline.partialDerivation': 'Partial derivation',
    'timeline.areaM2': 'Derived area (m²)',
    'timeline.empty': 'No stage or parcel link recorded.',
    'timeline.loadFailed': 'Could not load land history.',
    'timeline.saveFailed': 'Could not save stage or parcel link.',
    'subdivision.title': 'Split parcel boundary',
    'subdivision.enclosedMode': 'Interior parcel',
    'subdivision.edgeMode': 'Outer edge parcel',
    'subdivision.instruction': 'Tap each corner as in Google Earth. Sketches are measured independently and may share or slightly cross the source edge. Tap the first point or choose Close shape and preview.',
    'subdivision.reset': 'Redraw cut',
    'subdivision.fragment': 'Parcel',
    'subdivision.editSelected': 'Draw each small parcel inside the source area:',
    'subdivision.overview': 'All parcels:',
    'subdivision.undoPoint': 'Undo last point',
    'subdivision.autoFinish': 'Choose at least three corners, then tap the first point or close the shape.',
    'subdivision.closeOutline': 'Close shape and preview',
    'subdivision.distinctEnd': 'Add a second boundary point distinct from the start before closing.',
    'subdivision.closedBoundary': 'Parcel boundaries close automatically along the original boundary, with no gaps.',
    'subdivision.resetAll': 'Redraw all cuts',
    'subdivision.invalidCut': 'Cannot close this polygon. Use at least three corners without crossing its own edges.',
    'subdivision.preview': 'Areas of new parcels',
    'subdivision.locationRequired': 'The parcel location does not match the catalog; reconcile it first.',
    'subdivision.firstName': 'First parcel name',
    'subdivision.secondName': 'Second parcel name',
    'subdivision.save': 'Save all new parcels',
    'subdivision.loadFailed': 'Could not load source parcel.',
    'subdivision.saveFailed': 'Could not split parcel. Check boundary, location and names.',
    'household.directory': 'Household directory',
    'household.detail': 'Household details',
    'household.add': 'Add household',
    'household.edit': 'Edit household contact',
    'household.editScope': 'Code and location stay fixed. Names saved on existing parcels remain unchanged.',
    'household.codeAutomatic': 'An H00001… code will be assigned on save. Select a village from the catalog.',
    'household.noVillages': 'No valid village is available in the catalog.',
    'household.saveFailed': 'Could not save household. Check the details and try again.',
    'household.parcels': 'Household parcels',
    'household.noParcels': 'No parcels linked to this household.',
    'household.notFound': 'Household not found in this farm.',
    'household.search': 'Search code, name or village',
    'household.empty': 'No households yet.',
    'household.noMatches': 'No matching households.',
    'household.loadFailed': 'Could not load households.',
    'module.seasons': 'Seasons',
    'module.productionLogs': 'Production logs',
    'module.harvest': 'Harvest',
    'module.employees': 'Employees',
    'module.machines': 'Machines',
    'module.warehouse': 'Inventory',
    'module.fuel': 'Fuel',
    'module.costs': 'Production costs',
    'module.finance': 'Finance',
    'finance.receipt': 'Receipt',
    'finance.payment': 'Payment',
    'finance.add': 'Add document',
    'finance.category': 'Description',
    'finance.amount': 'Amount',
    'finance.currency': 'Currency',
    'finance.currency.lak': 'Lao kip (LAK)',
    'finance.currency.vnd': 'Vietnamese dong (VND)',
    'finance.currency.lak.short': 'kip',
    'finance.currency.vnd.short': 'dong',
    'finance.date': 'Document date',
    'finance.invalid': 'Enter a description and a positive whole amount.',
    'finance.saveFailed': 'Could not save document.',
    'module.resources': 'Machines & employees',
    'module.tasks': 'Tasks',
    'module.ai': 'AI assistant',
    'module.cloud': 'Cloud sync',
    'module.backup': 'Local backup',
    'backup.title': 'Back up local data',
    'backup.explanation': 'Export both databases, photos and local files into a password-encrypted backup. Keep it outside the phone.',
    'backup.externalFiles': 'Export fails if a referenced local file is missing. Older JSON backups are unencrypted.',
    'backup.newPasswordTitle': 'Set backup password',
    'backup.passwordTitle': 'Backup password',
    'backup.password': 'Password',
    'backup.confirmPassword': 'Confirm password',
    'backup.passwordAdvice': 'At least 12 characters. Keep it safe; a lost password cannot unlock the file.',
    'backup.passwordInvalid': 'Incorrect password or damaged encrypted file.',
    'backup.legacyTitle': 'Warning: unencrypted file',
    'backup.legacyUnencrypted': 'Older backup is unencrypted. Anyone with the file can read its contents.',
    'backup.export': 'Export backup',
    'backup.inspect': 'Inspect backup file',
    'backup.preflight': 'Test restore (no data changes)',
    'backup.preflightValid': 'Restore test passed. Current data is unchanged. Rows by table:',
    'backup.preflightFailed': 'Cannot restore: incomplete backup, mismatched schema or invalid relationships.',
    'backup.preflight.missingCosts': 'Older backup has no costs database. Export a new backup and retry.',
    'backup.preflight.schemaVersion': 'Backup database version differs from this app.',
    'backup.preflight.tables': 'Backup tables differ from this app.',
    'backup.preflight.sqlite': 'Could not rebuild the backup in temporary SQLite.',
    'backup.preflight.integrity': 'Temporary SQLite integrity check failed.',
    'backup.preflight.foreignKeys': 'Backup contains invalid foreign key references.',
    'backup.apply': 'Restore on next app launch',
    'backup.applyTitle': 'Confirm replacing device data',
    'backup.applyWarning': 'The next app launch will replace both databases with this backup. Changes since the backup will be lost. Only local files packaged in a v3 backup are restored. Keep a separate backup before continuing.',
    'backup.applyConfirm': 'Confirm restore',
    'backup.scheduled': 'Prepared. Fully close and reopen the app to apply.',
    'backup.applied': 'Both databases restored. Check your records.',
    'backup.previous': 'View data before restore',
    'backup.applyFailed': 'Restore failed. The transaction was rolled back; check the current records.',
    'backup.valid': 'Valid file. Rows by table:',
    'backup.invalid': 'Invalid or damaged backup file.',
    'backup.exportFailed': 'Could not export backup.',
    'module.administrativeCatalog': 'Administrative areas',
    'admin.title': 'Administrative areas',
    'admin.add': 'Add area',
    'admin.level': 'Level',
    'admin.parent': 'Parent area',
    'admin.name': 'Area name',
    'admin.code': 'Internal code',
    'admin.alternate': 'Other name (optional)',
    'admin.province': 'Province',
    'admin.district': 'District',
    'admin.village': 'Village',
    'admin.country': 'Country',
    'admin.root': 'Root',
    'admin.parentRequired': 'Select a parent area.',
    'admin.saveFailed': 'Could not save. Check the name, code, and duplicate codes under this parent.',
    'admin.loadFailed': 'Could not load administrative areas.',
    'admin.internalCodes': 'AGRICO internal codes; existing codes stay unchanged.',
    'quickCreate.logs': 'Log',
    'quickCreate.harvest': 'Harvest',
    'quickCreate.costs': 'Cost',
    'quickCreate.employees': 'Employee',
    'quickCreate.machines': 'Machine',
    'quickCreate.tasks': 'Task',
    'quickCreate.other': 'Other',
    'profile.title': 'Profile',
    'profile.language': 'Language',
    'profile.settings': 'Settings',
    'common.unavailable': 'Unavailable',
    'common.empty': 'No data yet',
    'common.open': 'Open',
    'startup.error': 'AGRICO could not start.',
    'parcel.boundaryRequired':
        'Measure with GPS or import KML/KMZ before creating the parcel.',
    'export.unavailable': 'The exported file could not be saved or opened.',
    'gps.permissionDenied': 'Location permission was denied.',
  };

  static const Map<String, Map<String, String>> _catalogue = {
    'vi': {
      ..._shellVi,
      'app.name': 'AGRICO ERP',
      'app.tagline': 'Quản lý nông nghiệp thông minh',
      'auth.username': 'Email / Tên đăng nhập',
      'auth.password': 'Mật khẩu',
      'auth.forgotPassword': 'Quên mật khẩu?',
      'auth.signIn': 'ĐĂNG NHẬP',
      'auth.demoHint': '💡 (Nhấn nút để vào Demo, không cần mật khẩu)',
      'common.loading': 'Đang tải…',
      'common.retry': 'Thử lại',
      'common.cancel': 'Hủy',
      'common.save': 'Lưu',
      'error.unauthorized': 'Bạn không có quyền thực hiện thao tác này.',
      'error.permissionDenied': 'Bạn không có quyền thực hiện thao tác này.',
      'landParcel.create.success': 'Đã tạo lô đất.',
      'landParcel.update.success': 'Đã cập nhật thông tin lô đất.',
      'landParcel.error.notFound': 'Không tìm thấy lô đất.',
      'landParcel.geometry.invalid': 'Ranh giới lô đất không hợp lệ.',
      'landParcel.persistence.failed': 'Không thể lưu thay đổi lô đất.',
      'landParcel.boundary.verifiedConfirmation':
          'Ranh giới đã được xác minh. Hãy xác nhận trước khi thay thế.',
      'landParcel.boundary.replaceSuccess': 'Đã cập nhật ranh giới lô đất.',
      'landParcel.boundary.verifySuccess': 'Đã cập nhật trạng thái xác minh.',
      'boundary.verify.action': 'Xác minh ranh giới',
      'boundary.verify.confirmTitle': 'Xác minh ranh giới?',
      'boundary.verify.confirmMessage':
          'Sau khi xác minh, việc thay đổi ranh giới sẽ yêu cầu xác nhận rõ ràng.',
      'landParcel.gps.invalidSource': 'Nguồn đo GPS không hợp lệ.',
      'landParcel.import.previewReady':
          'Đã chuẩn bị bản xem trước nhập dữ liệu.',
      'landParcel.import.failed': 'Không thể đọc tệp KML/KMZ.',
      'landParcel.export.success': 'Đã xuất tệp KML/KMZ.',
      'landParcel.export.failed': 'Không thể xuất tệp KML/KMZ.',
      'landParcel.preview.warning': 'Hãy kiểm tra cảnh báo trước khi xác nhận.',
      'survey.household': 'Hộ gia đình',
      'survey.administrativeLocation': 'Địa chỉ hành chính',
      'survey.landUse': 'Mục đích sử dụng đất',
      'survey.landCondition': 'Hiện trạng đất',
      'survey.clearingStatus': 'Tình trạng phát quang',
      'survey.readinessStatus': 'Mức độ sẵn sàng',
      'survey.crop': 'Cây trồng',
      'survey.cropCondition': 'Tình trạng cây trồng',
      'survey.quantityUnit': 'Số lượng và đơn vị',
      'survey.record': 'Khảo sát đất',
      'survey.surveyor': 'Người khảo sát',
      'survey.attachment': 'Tệp đính kèm',
      'survey.validation.invalid': 'Dữ liệu khảo sát không hợp lệ.',
      'survey.persistence.failed': 'Không thể lưu dữ liệu khảo sát.',
      'common.all': 'Tất cả',
      'common.active': 'Đang hoạt động',
      'common.inactive': 'Ngừng hoạt động',
      'common.edit': 'Sửa',
      'common.remove': 'Xóa',
      'common.confirm': 'Xác nhận',
      'parcel.list.title': 'Danh sách lô đất',
      'parcel.list.empty': 'Chưa có lô đất.',
      'parcel.list.error': 'Không thể tải danh sách lô đất.',
      'parcel.detail.error': 'Không thể tải chi tiết lô đất.',
      'parcel.search': 'Tìm lô đất',
      'parcel.filter.active': 'Trạng thái',
      'parcel.filter.verification': 'Xác minh',
      'parcel.create.action': 'Tạo lô đất',
      'parcel.create.title': 'Tạo hồ sơ lô đất',
      'parcel.edit.title': 'Sửa hồ sơ lô đất',
      'parcel.code': 'Mã khoảnh',
      'parcel.code.autoOnSave': 'Mã thửa tự tạo khi lưu',
      'parcel.name': 'Tên lô đất',
      'parcel.section.identity': 'Thông tin lô đất',
      'parcel.section.overview': 'Tổng quan',
      'parcel.section.boundary': 'Ranh giới và đo đạc',
      'location.country': 'Quốc gia',
      'location.province': 'Tỉnh',
      'location.district': 'Huyện',
      'location.village': 'Bản',
      'household.code': 'Mã hộ',
      'household.createNew': 'Tạo hộ mới · tự cấp mã',
      'household.head': 'Chủ hộ',
      'household.phone': 'Điện thoại',
      'household.alternativeContact': 'Liên hệ khác',
      'geometry.areaM2': 'Diện tích m²',
      'geometry.areaHa': 'Diện tích ha',
      'geometry.perimeter': 'Chu vi',
      'geometry.centroid': 'Tâm thửa',
      'geometry.accuracy': 'Độ chính xác',
      'geometry.confidence': 'Độ tin cậy',
      'boundary.source': 'Nguồn ranh giới',
      'boundary.version': 'Phiên bản',
      'boundary.history.title': 'Lịch sử ranh giới',
      'boundary.reconciliation.required': 'Ranh giới thửa đất và dữ liệu không gian chưa khớp. Cần đối soát trước khi xuất KML/KMZ.',
      'boundary.reconciliation.eligible': 'Dữ liệu không gian đã khớp. Có thể gắn lại mã không gian còn thiếu cho thửa cũ.',
      'boundary.reconciliation.action': 'Gắn lại mã không gian',
      'boundary.reconciliation.confirm': 'Chỉ gắn mã không gian còn thiếu cho thửa này nếu kiểm tra lại dữ liệu vẫn khớp. Tiếp tục?',
      'boundary.reconciliation.success': 'Đã gắn lại mã không gian cho thửa đất.',
      'boundary.reconciliation.manual': 'Dữ liệu đã thay đổi hoặc chưa khớp. Cần đối soát thủ công.',
      'boundary.audit.visibleSummary': 'Tình trạng ranh giới của các thửa đang hiển thị',
      'boundary.audit.filter': 'Lọc theo tình trạng ranh giới',
      'boundary.audit.unlinked': 'Chưa liên kết không gian',
      'boundary.audit.consistent': 'Khớp dữ liệu không gian',
      'boundary.audit.repairableLegacyIdentity': 'Có thể gắn lại mã',
      'boundary.audit.needsReconciliation': 'Cần đối soát thủ công',
      'boundary.issue.missingLink': 'Thiếu liên kết với dữ liệu không gian.',
      'boundary.issue.identityMismatch': 'Mã không gian của thửa và liên kết không khớp.',
      'boundary.issue.missingFeature': 'Không tìm thấy đối tượng không gian đã liên kết.',
      'boundary.issue.wrongFeatureType': 'Đối tượng đã liên kết không phải thửa đất.',
      'boundary.issue.missingRevision': 'Không tìm thấy phiên bản không gian hiện tại.',
      'boundary.issue.invalidGeometry': 'Thiếu hình học đa giác trong đối tượng hoặc phiên bản.',
      'boundary.issue.missingBoundaryVersion': 'Không tìm thấy đúng một phiên bản ranh giới hiện tại.',
      'boundary.issue.boundaryReferenceMismatch': 'Phiên bản không gian tham chiếu sai lịch sử ranh giới.',
      'boundary.issue.boundaryGeometryMismatch': 'Hình học ranh giới của thửa và không gian không khớp.',
      'boundary.source.gps': 'GPS',
      'boundary.source.googleEarth': 'Google Earth',
      'boundary.source.manual': 'Thủ công',
      'boundary.source.cad': 'CAD',
      'boundary.source.imported': 'Nhập dữ liệu',
      'verification.draft': 'Bản nháp',
      'verification.measured': 'Đã đo',
      'verification.verified': 'Đã xác minh',
      'verification.rejected': 'Bị từ chối',
      'verification.confirm.title': 'Thay ranh giới đã xác minh?',
      'crop.empty': 'Chưa có cây trồng.',
      'crop.add': 'Thêm cây trồng',
      'crop.edit': 'Sửa cây trồng',
      'crop.type': 'Loại cây',
      'crop.quantity': 'Số lượng',
      'crop.unit': 'Đơn vị',
      'crop.age': 'Tuổi khi ghi nhận',
      'crop.age.years': 'năm',
      'crop.age.months': 'tháng',
      'crop.age.yearsInput': 'Tuổi cây (năm)',
      'crop.age.monthsInput': 'Tháng lẻ (0–11)',
      'crop.age.invalid': 'Số tháng lẻ phải từ 0 đến 11.',
      'crop.validation.failed': 'Kiểm tra loại cây, số lượng và đơn vị.',
      'crop.condition.unknown': 'Chưa rõ',
      'crop.condition.planned': 'Dự kiến',
      'crop.condition.growing': 'Đang sinh trưởng',
      'crop.condition.healthy': 'Tốt',
      'crop.condition.stressed': 'Sinh trưởng kém',
      'crop.condition.harvested': 'Đã thu hoạch',
      'survey.empty': 'Chưa có khảo sát.',
      'attachment.empty': 'Chưa có tệp đính kèm.',
      'googleEarth.title': 'Google Earth',
      'googleEarth.import': 'Nhập KML/KMZ',
      'googleEarth.exportKml': 'Xuất KML',
      'googleEarth.exportKmz': 'Xuất KMZ',
      'googleEarth.open': 'Mở bằng Google Earth',
      'googleEarth.openSuccess': 'Đã mở tệp ranh giới.',
      'googleEarth.openUnavailable':
          'Không tìm thấy ứng dụng phù hợp để mở tệp.',
      'gps.preview.title': 'Xem trước đo GPS',
      'gps.start': 'Đo GPS',
      'gps.confirm': 'Áp dụng ranh giới GPS',
      'import.preview.title': 'Xem trước dữ liệu nhập',
      'import.warning.missingAgricoMetadata': 'Tệp không có metadata AGRICO.',
      'validation.required': 'Trường này là bắt buộc.',
      'attachment.addMetadata': 'Thêm ảnh / tài liệu',
      'attachment.saveFailed': 'Không lưu được tệp đính kèm.',
      'attachment.openFailed': 'Không mở được tệp đính kèm.',
      'landUse.agricultural': 'Nông nghiệp',
      'landUse.residential': 'Đất ở',
      'landUse.forest': 'Rừng',
      'landUse.pasture': 'Đồng cỏ',
      'landUse.mixed': 'Hỗn hợp',
      'landUse.other': 'Khác',
      'landCondition.unknown': 'Chưa rõ',
      'landCondition.unused': 'Chưa sử dụng',
      'landCondition.cultivated': 'Đang canh tác',
      'landCondition.degraded': 'Suy thoái',
      'landCondition.flooded': 'Ngập nước',
      'landCondition.other': 'Khác',
      'clearing.unknown': 'Chưa rõ',
      'clearing.notRequired': 'Không cần',
      'clearing.notStarted': 'Chưa phát quang',
      'clearing.partial': 'Một phần',
      'clearing.completed': 'Hoàn tất',
      'readiness.unknown': 'Chưa rõ',
      'readiness.notReady': 'Chưa sẵn sàng',
      'readiness.preparation': 'Đang chuẩn bị',
      'readiness.ready': 'Sẵn sàng',
    },
    'lo': {
      ..._shellLo,
      'app.name': 'AGRICO ERP',
      'app.tagline': 'ການຈັດການກະສິກຳອັດສະລິຍະ',
      'auth.username': 'ອີເມວ / ຊື່ຜູ້ໃຊ້',
      'auth.password': 'ລະຫັດຜ່ານ',
      'auth.forgotPassword': 'ລືມລະຫັດຜ່ານ?',
      'auth.signIn': 'ເຂົ້າລະບົບ',
      'auth.demoHint': '💡 (ກົດປຸ່ມເພື່ອເຂົ້າ Demo ໂດຍບໍ່ຕ້ອງໃສ່ລະຫັດ)',
      'common.loading': 'ກຳລັງໂຫຼດ…',
      'common.retry': 'ລອງໃໝ່',
      'common.cancel': 'ຍົກເລີກ',
      'common.save': 'ບັນທຶກ',
      'error.unauthorized': 'ທ່ານບໍ່ມີສິດເຮັດລາຍການນີ້.',
      'error.permissionDenied': 'ທ່ານບໍ່ມີສິດເຮັດລາຍການນີ້.',
      'landParcel.create.success': 'ສ້າງແປງດິນແລ້ວ.',
      'landParcel.update.success': 'ອັບເດດຂໍ້ມູນແປງດິນແລ້ວ.',
      'landParcel.error.notFound': 'ບໍ່ພົບແປງດິນ.',
      'landParcel.geometry.invalid': 'ເຂດແດນແປງດິນບໍ່ຖືກຕ້ອງ.',
      'landParcel.persistence.failed': 'ບໍ່ສາມາດບັນທຶກການປ່ຽນແປງໄດ້.',
      'landParcel.boundary.verifiedConfirmation':
          'ເຂດແດນນີ້ຖືກຢືນຢັນແລ້ວ. ກະລຸນາຢືນຢັນກ່ອນປ່ຽນແທນ.',
      'landParcel.boundary.replaceSuccess': 'ອັບເດດເຂດແດນແລ້ວ.',
      'landParcel.boundary.verifySuccess': 'ອັບເດດສະຖານະການຢືນຢັນແລ້ວ.',
      'boundary.verify.action': 'ຢືນຢັນເຂດແດນ',
      'boundary.verify.confirmTitle': 'ຢືນຢັນເຂດແດນບໍ?',
      'boundary.verify.confirmMessage':
          'ຫຼັງຈາກຢືນຢັນແລ້ວ ການປ່ຽນແທນເຂດແດນນີ້ຈະຕ້ອງມີການຢືນຢັນຢ່າງຊັດເຈນ.',
      'landParcel.gps.invalidSource': 'ແຫຼ່ງຂໍ້ມູນ GPS ບໍ່ຖືກຕ້ອງ.',
      'landParcel.import.previewReady': 'ກຽມຕົວຢ່າງກ່ອນນຳເຂົ້າແລ້ວ.',
      'landParcel.import.failed': 'ບໍ່ສາມາດອ່ານໄຟລ໌ KML/KMZ.',
      'landParcel.export.success': 'ສົ່ງອອກໄຟລ໌ KML/KMZ ແລ້ວ.',
      'landParcel.export.failed': 'ບໍ່ສາມາດສົ່ງອອກ KML/KMZ.',
      'landParcel.preview.warning': 'ກະລຸນາກວດຄຳເຕືອນກ່ອນຢືນຢັນ.',
      'survey.household': 'ຄົວເຮືອນ',
      'survey.administrativeLocation': 'ທີ່ຢູ່ປົກຄອງ',
      'survey.landUse': 'ການນຳໃຊ້ທີ່ດິນ',
      'survey.landCondition': 'ສະພາບທີ່ດິນ',
      'survey.clearingStatus': 'ສະຖານະການຖາງ',
      'survey.readinessStatus': 'ຄວາມພ້ອມ',
      'survey.crop': 'ພືດປູກ',
      'survey.cropCondition': 'ສະພາບພືດ',
      'survey.quantityUnit': 'ຈຳນວນ ແລະ ຫົວໜ່ວຍ',
      'survey.record': 'ການສຳຫຼວດທີ່ດິນ',
      'survey.surveyor': 'ຜູ້ສຳຫຼວດ',
      'survey.attachment': 'ໄຟລ໌ແນບ',
      'survey.validation.invalid': 'ຂໍ້ມູນສຳຫຼວດບໍ່ຖືກຕ້ອງ.',
      'survey.persistence.failed': 'ບໍ່ສາມາດບັນທຶກຂໍ້ມູນສຳຫຼວດ.',
      'common.all': 'ທັງໝົດ',
      'common.active': 'ໃຊ້ງານ',
      'common.inactive': 'ບໍ່ໃຊ້ງານ',
      'common.edit': 'ແກ້ໄຂ',
      'common.remove': 'ລຶບ',
      'common.confirm': 'ຢືນຢັນ',
      'parcel.list.title': 'ລາຍການແປງດິນ',
      'parcel.list.empty': 'ຍັງບໍ່ມີແປງດິນ.',
      'parcel.list.error': 'ບໍ່ສາມາດໂຫຼດລາຍການແປງດິນ.',
      'parcel.detail.error': 'ບໍ່ສາມາດໂຫຼດລາຍລະອຽດແປງດິນ.',
      'parcel.search': 'ຄົ້ນຫາແປງດິນ',
      'parcel.filter.active': 'ສະຖານະ',
      'parcel.filter.verification': 'ການຢືນຢັນ',
      'parcel.create.action': 'ສ້າງແປງດິນ',
      'parcel.create.title': 'ສ້າງຂໍ້ມູນແປງດິນ',
      'parcel.edit.title': 'ແກ້ໄຂແປງດິນ',
      'parcel.code': 'ລະຫັດແປງ',
      'parcel.code.autoOnSave': 'ສ້າງລະຫັດແປງເມື່ອບັນທຶກ',
      'parcel.name': 'ຊື່ແປງດິນ',
      'parcel.section.identity': 'ຂໍ້ມູນແປງດິນ',
      'parcel.section.overview': 'ພາບລວມ',
      'parcel.section.boundary': 'ເຂດແດນ ແລະ ການວັດແທກ',
      'location.country': 'ປະເທດ',
      'location.province': 'ແຂວງ',
      'location.district': 'ເມືອງ',
      'location.village': 'ບ້ານ',
      'household.code': 'ລະຫັດຄົວເຮືອນ',
      'household.createNew': 'ສ້າງຄົວເຮືອນໃໝ່ · ອອກລະຫັດອັດຕະໂນມັດ',
      'household.head': 'ຫົວໜ້າຄົວເຮືອນ',
      'household.phone': 'ໂທລະສັບ',
      'household.alternativeContact': 'ຕິດຕໍ່ອື່ນ',
      'geometry.areaM2': 'ເນື້ອທີ່ m²',
      'geometry.areaHa': 'ເນື້ອທີ່ ha',
      'geometry.perimeter': 'ຄວາມຍາວຮອບ',
      'geometry.centroid': 'ຈຸດສູນກາງ',
      'geometry.accuracy': 'ຄວາມຊັດເຈນ',
      'geometry.confidence': 'ຄວາມໝັ້ນໃຈ',
      'boundary.source': 'ແຫຼ່ງເຂດແດນ',
      'boundary.version': 'ສະບັບ',
      'boundary.history.title': 'ປະຫວັດເຂດແດນ',
      'boundary.reconciliation.required': 'ເຂດແດນແປງດິນ ແລະ ຂໍ້ມູນແຜນທີ່ບໍ່ກົງກັນ. ຕ້ອງກວດສອບກ່ອນສົ່ງອອກ KML/KMZ.',
      'boundary.reconciliation.eligible': 'ຂໍ້ມູນແຜນທີ່ກົງກັນແລ້ວ. ສາມາດຄືນຄ່າລະຫັດແຜນທີ່ທີ່ຂາດໃຫ້ແປງດິນເກົ່າ.',
      'boundary.reconciliation.action': 'ຄືນຄ່າລະຫັດແຜນທີ່',
      'boundary.reconciliation.confirm': 'ຄືນຄ່າລະຫັດທີ່ຂາດໃຫ້ແປງນີ້ ເມື່ອກວດຂໍ້ມູນແລ້ວວ່າກົງກັນ. ສືບຕໍ່ບໍ?',
      'boundary.reconciliation.success': 'ຄືນຄ່າລະຫັດແຜນທີ່ໃຫ້ແປງດິນແລ້ວ.',
      'boundary.reconciliation.manual': 'ຂໍ້ມູນປ່ຽນໄປ ຫຼື ຍັງບໍ່ກົງກັນ. ຕ້ອງກວດສອບດ້ວຍມື.',
      'boundary.audit.visibleSummary': 'ສະຖານະເຂດແດນຂອງແປງທີ່ສະແດງ',
      'boundary.audit.filter': 'ກັ່ນຕອງຕາມສະຖານະເຂດແດນ',
      'boundary.audit.unlinked': 'ຍັງບໍ່ເຊື່ອມຂໍ້ມູນແຜນທີ່',
      'boundary.audit.consistent': 'ຂໍ້ມູນກົງກັນ',
      'boundary.audit.repairableLegacyIdentity': 'ສາມາດຄືນຄ່າລະຫັດ',
      'boundary.audit.needsReconciliation': 'ຕ້ອງກວດສອບດ້ວຍມື',
      'boundary.issue.missingLink': 'ບໍ່ມີການເຊື່ອມກັບຂໍ້ມູນແຜນທີ່.',
      'boundary.issue.identityMismatch': 'ລະຫັດແຜນທີ່ຂອງແປງ ແລະ ຂໍ້ມູນເຊື່ອມບໍ່ກົງກັນ.',
      'boundary.issue.missingFeature': 'ບໍ່ພົບລາຍການແຜນທີ່ທີ່ເຊື່ອມໄວ້.',
      'boundary.issue.wrongFeatureType': 'ລາຍການແຜນທີ່ທີ່ເຊື່ອມບໍ່ແມ່ນແປງດິນ.',
      'boundary.issue.missingRevision': 'ບໍ່ພົບສະບັບແຜນທີ່ປັດຈຸບັນ.',
      'boundary.issue.invalidGeometry': 'ຂາດຮູບຊົງຫຼາຍຫຼ່ຽມໃນລາຍການ ຫຼື ສະບັບ.',
      'boundary.issue.missingBoundaryVersion': 'ບໍ່ພົບສະບັບເຂດແດນປັດຈຸບັນທີ່ຖືກຕ້ອງ.',
      'boundary.issue.boundaryReferenceMismatch': 'ສະບັບແຜນທີ່ອ້າງອີງປະຫວັດເຂດແດນບໍ່ກົງກັນ.',
      'boundary.issue.boundaryGeometryMismatch': 'ຮູບຊົງເຂດແດນຂອງແປງ ແລະ ແຜນທີ່ບໍ່ກົງກັນ.',
      'boundary.source.gps': 'GPS',
      'boundary.source.googleEarth': 'Google Earth',
      'boundary.source.manual': 'ກຳນົດເອງ',
      'boundary.source.cad': 'CAD',
      'boundary.source.imported': 'ນຳເຂົ້າ',
      'verification.draft': 'ຮ່າງ',
      'verification.measured': 'ວັດແທກແລ້ວ',
      'verification.verified': 'ຢືນຢັນແລ້ວ',
      'verification.rejected': 'ຖືກປະຕິເສດ',
      'verification.confirm.title': 'ປ່ຽນເຂດແດນທີ່ຢືນຢັນແລ້ວ?',
      'crop.empty': 'ຍັງບໍ່ມີພືດ.',
      'crop.add': 'ເພີ່ມພືດ',
      'crop.edit': 'ແກ້ໄຂພືດ',
      'crop.type': 'ຊະນິດພືດ',
      'crop.quantity': 'ຈຳນວນ',
      'crop.unit': 'ຫົວໜ່ວຍ',
      'crop.age': 'ອາຍຸເມື່ອບັນທຶກ',
      'crop.age.years': 'ປີ',
      'crop.age.months': 'ເດືອນ',
      'crop.age.yearsInput': 'ອາຍຸພືດ (ປີ)',
      'crop.age.monthsInput': 'ເດືອນເພີ່ມ (0–11)',
      'crop.age.invalid': 'ເດືອນເພີ່ມຕ້ອງຢູ່ລະຫວ່າງ 0 ຫາ 11.',
      'crop.validation.failed': 'ກວດເບິ່ງຊະນິດພືດ, ຈຳນວນ ແລະ ຫົວໜ່ວຍ.',
      'crop.condition.unknown': 'ບໍ່ຮູ້',
      'crop.condition.planned': 'ວາງແຜນ',
      'crop.condition.growing': 'ກຳລັງເຕີບໂຕ',
      'crop.condition.healthy': 'ດີ',
      'crop.condition.stressed': 'ບໍ່ແຂງແຮງ',
      'crop.condition.harvested': 'ເກັບກ່ຽວແລ້ວ',
      'survey.empty': 'ຍັງບໍ່ມີການສຳຫຼວດ.',
      'attachment.empty': 'ຍັງບໍ່ມີໄຟລ໌ແນບ.',
      'googleEarth.title': 'Google Earth',
      'googleEarth.import': 'ນຳເຂົ້າ KML/KMZ',
      'googleEarth.exportKml': 'ສົ່ງອອກ KML',
      'googleEarth.exportKmz': 'ສົ່ງອອກ KMZ',
      'googleEarth.open': 'ເປີດດ້ວຍ Google Earth',
      'googleEarth.openSuccess': 'ເປີດໄຟລ໌ເຂດແດນແລ້ວ.',
      'googleEarth.openUnavailable': 'ບໍ່ພົບແອັບທີ່ສາມາດເປີດໄຟລ໌ນີ້.',
      'gps.preview.title': 'ຕົວຢ່າງການວັດ GPS',
      'gps.start': 'ວັດແທກ GPS',
      'gps.confirm': 'ນຳໃຊ້ເຂດແດນ GPS',
      'import.preview.title': 'ຕົວຢ່າງກ່ອນນຳເຂົ້າ',
      'import.warning.missingAgricoMetadata': 'ໄຟລ໌ບໍ່ມີ metadata AGRICO.',
      'validation.required': 'ຈຳເປັນຕ້ອງປ້ອນຂໍ້ມູນນີ້.',
      'attachment.addMetadata': 'ເພີ່ມຮູບ / ເອກະສານ',
      'attachment.saveFailed': 'ບັນທຶກໄຟລ໌ແນບບໍ່ໄດ້.',
      'attachment.openFailed': 'ເປີດໄຟລ໌ແນບບໍ່ໄດ້.',
      'landUse.agricultural': 'ກະສິກຳ',
      'landUse.residential': 'ທີ່ຢູ່ອາໄສ',
      'landUse.forest': 'ປ່າໄມ້',
      'landUse.pasture': 'ທົ່ງຫຍ້າ',
      'landUse.mixed': 'ປະສົມ',
      'landUse.other': 'ອື່ນໆ',
      'landCondition.unknown': 'ບໍ່ຮູ້',
      'landCondition.unused': 'ຍັງບໍ່ໃຊ້',
      'landCondition.cultivated': 'ກຳລັງປູກຝັງ',
      'landCondition.degraded': 'ເສື່ອມໂຊມ',
      'landCondition.flooded': 'ນ້ຳຖ້ວມ',
      'landCondition.other': 'ອື່ນໆ',
      'clearing.unknown': 'ບໍ່ຮູ້',
      'clearing.notRequired': 'ບໍ່ຈຳເປັນ',
      'clearing.notStarted': 'ຍັງບໍ່ຖາງ',
      'clearing.partial': 'ບາງສ່ວນ',
      'clearing.completed': 'ສຳເລັດ',
      'readiness.unknown': 'ບໍ່ຮູ້',
      'readiness.notReady': 'ຍັງບໍ່ພ້ອມ',
      'readiness.preparation': 'ກຳລັງກຽມ',
      'readiness.ready': 'ພ້ອມ',
    },
    'en': {
      ..._shellEn,
      'app.name': 'AGRICO ERP',
      'app.tagline': 'Smart agriculture management',
      'auth.username': 'Email / Username',
      'auth.password': 'Password',
      'auth.forgotPassword': 'Forgot password?',
      'auth.signIn': 'SIGN IN',
      'auth.demoHint': '💡 (Tap to enter the demo without a password)',
      'common.loading': 'Loading…',
      'common.retry': 'Retry',
      'common.cancel': 'Cancel',
      'common.save': 'Save',
      'error.unauthorized': 'You do not have permission for this action.',
      'error.permissionDenied': 'You do not have permission for this action.',
      'landParcel.create.success': 'Land parcel created.',
      'landParcel.update.success': 'Land parcel details updated.',
      'landParcel.error.notFound': 'Land parcel not found.',
      'landParcel.geometry.invalid': 'The land parcel boundary is invalid.',
      'landParcel.persistence.failed':
          'The land parcel change could not be saved.',
      'landParcel.boundary.verifiedConfirmation':
          'This boundary is verified. Confirm before replacing it.',
      'landParcel.boundary.replaceSuccess': 'Land parcel boundary updated.',
      'landParcel.boundary.verifySuccess': 'Verification status updated.',
      'boundary.verify.action': 'Verify boundary',
      'boundary.verify.confirmTitle': 'Verify boundary?',
      'boundary.verify.confirmMessage':
          'After verification, replacing this boundary will require explicit confirmation.',
      'landParcel.gps.invalidSource': 'The GPS measurement source is invalid.',
      'landParcel.import.previewReady': 'Import preview is ready.',
      'landParcel.import.failed': 'The KML/KMZ file could not be read.',
      'landParcel.export.success': 'KML/KMZ export is ready.',
      'landParcel.export.failed': 'The KML/KMZ file could not be exported.',
      'landParcel.preview.warning': 'Review warnings before confirming.',
      'survey.household': 'Household',
      'survey.administrativeLocation': 'Administrative location',
      'survey.landUse': 'Land use',
      'survey.landCondition': 'Land condition',
      'survey.clearingStatus': 'Clearing status',
      'survey.readinessStatus': 'Readiness status',
      'survey.crop': 'Crop',
      'survey.cropCondition': 'Crop condition',
      'survey.quantityUnit': 'Quantity and unit',
      'survey.record': 'Land survey',
      'survey.surveyor': 'Surveyor',
      'survey.attachment': 'Attachment',
      'survey.validation.invalid': 'The survey data is invalid.',
      'survey.persistence.failed': 'The survey data could not be saved.',
      'common.all': 'All',
      'common.active': 'Active',
      'common.inactive': 'Inactive',
      'common.edit': 'Edit',
      'common.remove': 'Remove',
      'common.confirm': 'Confirm',
      'parcel.list.title': 'Land parcels',
      'parcel.list.empty': 'No land parcels yet.',
      'parcel.list.error': 'Land parcels could not be loaded.',
      'parcel.detail.error': 'Land parcel details could not be loaded.',
      'parcel.search': 'Search parcels',
      'parcel.filter.active': 'Status',
      'parcel.filter.verification': 'Verification',
      'parcel.create.action': 'Create parcel',
      'parcel.create.title': 'Create land parcel',
      'parcel.edit.title': 'Edit land parcel',
      'parcel.code': 'Parcel code',
      'parcel.code.autoOnSave': 'Parcel code is assigned when saved',
      'parcel.name': 'Parcel name',
      'parcel.section.identity': 'Parcel information',
      'parcel.section.overview': 'Overview',
      'parcel.section.boundary': 'Boundary and measurement',
      'location.country': 'Country',
      'location.province': 'Province',
      'location.district': 'District',
      'location.village': 'Village / Ban',
      'household.code': 'Household code',
      'household.createNew': 'Create new household · assign code',
      'household.head': 'Head of household',
      'household.phone': 'Phone',
      'household.alternativeContact': 'Alternative contact',
      'geometry.areaM2': 'Area m²',
      'geometry.areaHa': 'Area ha',
      'geometry.perimeter': 'Perimeter',
      'geometry.centroid': 'Centroid',
      'geometry.accuracy': 'Accuracy',
      'geometry.confidence': 'Confidence',
      'boundary.source': 'Boundary source',
      'boundary.version': 'Version',
      'boundary.history.title': 'Boundary history',
      'boundary.reconciliation.required': 'Parcel boundary and spatial data disagree. Reconcile them before exporting KML/KMZ.',
      'boundary.reconciliation.eligible': 'Spatial data matches. The missing spatial ID on this legacy parcel can be restored.',
      'boundary.reconciliation.action': 'Restore spatial ID',
      'boundary.reconciliation.confirm': 'Restore only this parcel’s missing spatial ID if the data still matches. Continue?',
      'boundary.reconciliation.success': 'The parcel’s spatial ID has been restored.',
      'boundary.reconciliation.manual': 'The data changed or does not match. Manual reconciliation is required.',
      'boundary.audit.visibleSummary': 'Boundary status of visible parcels',
      'boundary.audit.filter': 'Filter by boundary status',
      'boundary.audit.unlinked': 'Not linked to spatial data',
      'boundary.audit.consistent': 'Spatial data consistent',
      'boundary.audit.repairableLegacyIdentity': 'Spatial ID can be restored',
      'boundary.audit.needsReconciliation': 'Manual reconciliation needed',
      'boundary.issue.missingLink': 'The spatial link is missing.',
      'boundary.issue.identityMismatch': 'The parcel and link have different spatial IDs.',
      'boundary.issue.missingFeature': 'The linked spatial feature is missing.',
      'boundary.issue.wrongFeatureType': 'The linked spatial feature is not a parcel.',
      'boundary.issue.missingRevision': 'The current spatial revision is missing.',
      'boundary.issue.invalidGeometry': 'Polygon geometry is missing from the feature or revision.',
      'boundary.issue.missingBoundaryVersion': 'The current boundary history version is missing or duplicated.',
      'boundary.issue.boundaryReferenceMismatch': 'The spatial revision references another boundary history entry.',
      'boundary.issue.boundaryGeometryMismatch': 'The parcel and spatial polygon boundaries differ.',
      'boundary.source.gps': 'GPS',
      'boundary.source.googleEarth': 'Google Earth',
      'boundary.source.manual': 'Manual',
      'boundary.source.cad': 'CAD',
      'boundary.source.imported': 'Imported',
      'verification.draft': 'Draft',
      'verification.measured': 'Measured',
      'verification.verified': 'Verified',
      'verification.rejected': 'Rejected',
      'verification.confirm.title': 'Replace verified boundary?',
      'crop.empty': 'No crops.',
      'crop.add': 'Add crop',
      'crop.edit': 'Edit crop',
      'crop.type': 'Crop type',
      'crop.quantity': 'Quantity',
      'crop.unit': 'Unit',
      'crop.age': 'Age when recorded',
      'crop.age.years': 'years',
      'crop.age.months': 'months',
      'crop.age.yearsInput': 'Crop age (years)',
      'crop.age.monthsInput': 'Additional months (0–11)',
      'crop.age.invalid': 'Additional months must be from 0 to 11.',
      'crop.validation.failed': 'Check the crop type, quantity and unit.',
      'crop.condition.unknown': 'Unknown',
      'crop.condition.planned': 'Planned',
      'crop.condition.growing': 'Growing',
      'crop.condition.healthy': 'Healthy',
      'crop.condition.stressed': 'Stressed',
      'crop.condition.harvested': 'Harvested',
      'survey.empty': 'No surveys.',
      'attachment.empty': 'No attachments.',
      'googleEarth.title': 'Google Earth',
      'googleEarth.import': 'Import KML/KMZ',
      'googleEarth.exportKml': 'Export KML',
      'googleEarth.exportKmz': 'Export KMZ',
      'googleEarth.open': 'Open in Google Earth',
      'googleEarth.openSuccess': 'Boundary file opened.',
      'googleEarth.openUnavailable':
          'No compatible app is available to open this file.',
      'gps.preview.title': 'GPS measurement preview',
      'gps.start': 'Measure with GPS',
      'gps.confirm': 'Apply GPS boundary',
      'import.preview.title': 'Import preview',
      'import.warning.missingAgricoMetadata':
          'This file has no AGRICO metadata.',
      'validation.required': 'This field is required.',
      'attachment.addMetadata': 'Add photo / document',
      'attachment.saveFailed': 'Could not save attachment.',
      'attachment.openFailed': 'Could not open attachment.',
      'landUse.agricultural': 'Agricultural',
      'landUse.residential': 'Residential',
      'landUse.forest': 'Forest',
      'landUse.pasture': 'Pasture',
      'landUse.mixed': 'Mixed',
      'landUse.other': 'Other',
      'landCondition.unknown': 'Unknown',
      'landCondition.unused': 'Unused',
      'landCondition.cultivated': 'Cultivated',
      'landCondition.degraded': 'Degraded',
      'landCondition.flooded': 'Flooded',
      'landCondition.other': 'Other',
      'clearing.unknown': 'Unknown',
      'clearing.notRequired': 'Not required',
      'clearing.notStarted': 'Not started',
      'clearing.partial': 'Partial',
      'clearing.completed': 'Completed',
      'readiness.unknown': 'Unknown',
      'readiness.notReady': 'Not ready',
      'readiness.preparation': 'Preparation',
      'readiness.ready': 'Ready',
    },
  };

  String text(String key) {
    final languageCode = _catalogue.containsKey(locale.languageCode)
        ? locale.languageCode
        : 'vi';
    return _catalogue[languageCode]?[key] ?? _catalogue['vi']?[key] ?? key;
  }

  @visibleForTesting
  static Set<String> keysFor(Locale locale) =>
      _catalogue[locale.languageCode]?.keys.toSet() ?? const {};
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => AppLocalizations.supportedLocales.any(
    (supported) => supported.languageCode == locale.languageCode,
  );

  @override
  Future<AppLocalizations> load(Locale locale) =>
      SynchronousFuture(AppLocalizations(locale));

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

extension AppLocalizationsContext on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}
