import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

/// Lightweight localization facade used while legacy screens are migrated.
///
/// Keeping the catalogue in Dart makes the v2 foundation immediately usable
/// without coupling domain code to Flutter's generated localization classes.
class AppLocalizations {
  const AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = <Locale>[
    Locale('vi'),
    Locale('lo'),
    Locale('en'),
  ];

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    final value = Localizations.of<AppLocalizations>(context, AppLocalizations);
    assert(value != null, 'AppLocalizations is not registered in MaterialApp.');
    return value!;
  }

  static const Map<String, Map<String, String>> _catalogue = {
    'vi': {
      'app.name': 'AGRICO ERP',
      'app.tagline': 'Quản lý nông nghiệp thông minh',
      'auth.username': 'Email / Tên đăng nhập',
      'auth.password': 'Mật khẩu',
      'auth.forgotPassword': 'Quên mật khẩu?',
      'auth.signIn': 'ĐĂNG NHẬP',
      'auth.demoHint': '💡 (Nhấn nút để vào Demo, không cần mật khẩu)',
      'common.loading': 'Đang tải…',
      'common.retry': 'Thử lại',
      'common.cancel': 'Hủy',
      'common.save': 'Lưu',
      'error.unauthorized': 'Bạn không có quyền thực hiện thao tác này.',
      'error.permissionDenied': 'Bạn không có quyền thực hiện thao tác này.',
      'landParcel.create.success': 'Đã tạo lô đất.',
      'landParcel.update.success': 'Đã cập nhật thông tin lô đất.',
      'landParcel.error.notFound': 'Không tìm thấy lô đất.',
      'landParcel.geometry.invalid': 'Ranh giới lô đất không hợp lệ.',
      'landParcel.persistence.failed': 'Không thể lưu thay đổi lô đất.',
      'landParcel.boundary.verifiedConfirmation':
          'Ranh giới đã được xác minh. Hãy xác nhận trước khi thay thế.',
      'landParcel.boundary.replaceSuccess': 'Đã cập nhật ranh giới lô đất.',
      'landParcel.boundary.verifySuccess': 'Đã cập nhật trạng thái xác minh.',
      'landParcel.gps.invalidSource': 'Nguồn đo GPS không hợp lệ.',
      'landParcel.import.previewReady':
          'Đã chuẩn bị bản xem trước nhập dữ liệu.',
      'landParcel.import.failed': 'Không thể đọc tệp KML/KMZ.',
      'landParcel.export.success': 'Đã xuất tệp KML/KMZ.',
      'landParcel.export.failed': 'Không thể xuất tệp KML/KMZ.',
      'landParcel.preview.warning': 'Hãy kiểm tra cảnh báo trước khi xác nhận.',
      'survey.household': 'Hộ gia đình',
      'survey.administrativeLocation': 'Địa chỉ hành chính',
      'survey.landUse': 'Mục đích sử dụng đất',
      'survey.landCondition': 'Hiện trạng đất',
      'survey.clearingStatus': 'Tình trạng phát quang',
      'survey.readinessStatus': 'Mức độ sẵn sàng',
      'survey.crop': 'Cây trồng',
      'survey.cropCondition': 'Tình trạng cây trồng',
      'survey.quantityUnit': 'Số lượng và đơn vị',
      'survey.record': 'Khảo sát đất',
      'survey.surveyor': 'Người khảo sát',
      'survey.attachment': 'Tệp đính kèm',
      'survey.validation.invalid': 'Dữ liệu khảo sát không hợp lệ.',
      'survey.persistence.failed': 'Không thể lưu dữ liệu khảo sát.',
      'common.all': 'Tất cả',
      'common.active': 'Đang hoạt động',
      'common.inactive': 'Ngừng hoạt động',
      'common.edit': 'Sửa',
      'common.remove': 'Xóa',
      'common.confirm': 'Xác nhận',
      'parcel.list.title': 'Danh sách lô đất',
      'parcel.list.empty': 'Chưa có lô đất.',
      'parcel.list.error': 'Không thể tải danh sách lô đất.',
      'parcel.detail.error': 'Không thể tải chi tiết lô đất.',
      'parcel.search': 'Tìm lô đất',
      'parcel.filter.active': 'Trạng thái',
      'parcel.filter.verification': 'Xác minh',
      'parcel.create.action': 'Tạo lô đất',
      'parcel.create.title': 'Tạo hồ sơ lô đất',
      'parcel.edit.title': 'Sửa hồ sơ lô đất',
      'parcel.code': 'Mã khoảnh',
      'parcel.name': 'Tên lô đất',
      'parcel.section.identity': 'Thông tin lô đất',
      'parcel.section.overview': 'Tổng quan',
      'parcel.section.boundary': 'Ranh giới và đo đạc',
      'location.country': 'Quốc gia',
      'location.province': 'Tỉnh',
      'location.district': 'Huyện',
      'location.village': 'Bản',
      'household.code': 'Mã hộ',
      'household.head': 'Chủ hộ',
      'household.phone': 'Điện thoại',
      'household.alternativeContact': 'Liên hệ khác',
      'geometry.areaM2': 'Diện tích m²',
      'geometry.areaHa': 'Diện tích ha',
      'geometry.perimeter': 'Chu vi',
      'geometry.centroid': 'Tâm thửa',
      'geometry.accuracy': 'Độ chính xác',
      'geometry.confidence': 'Độ tin cậy',
      'boundary.source': 'Nguồn ranh giới',
      'boundary.version': 'Phiên bản',
      'boundary.history.title': 'Lịch sử ranh giới',
      'boundary.source.gps': 'GPS',
      'boundary.source.googleEarth': 'Google Earth',
      'boundary.source.manual': 'Thủ công',
      'boundary.source.cad': 'CAD',
      'boundary.source.imported': 'Nhập dữ liệu',
      'verification.draft': 'Bản nháp',
      'verification.measured': 'Đã đo',
      'verification.verified': 'Đã xác minh',
      'verification.rejected': 'Bị từ chối',
      'verification.confirm.title': 'Thay ranh giới đã xác minh?',
      'crop.empty': 'Chưa có cây trồng.',
      'crop.add': 'Thêm cây trồng',
      'crop.edit': 'Sửa cây trồng',
      'crop.type': 'Loại cây',
      'crop.quantity': 'Số lượng',
      'crop.unit': 'Đơn vị',
      'crop.condition.unknown': 'Chưa rõ',
      'crop.condition.planned': 'Dự kiến',
      'crop.condition.growing': 'Đang sinh trưởng',
      'crop.condition.healthy': 'Tốt',
      'crop.condition.stressed': 'Sinh trưởng kém',
      'crop.condition.harvested': 'Đã thu hoạch',
      'survey.empty': 'Chưa có khảo sát.',
      'attachment.empty': 'Chưa có tệp đính kèm.',
      'googleEarth.title': 'Google Earth',
      'googleEarth.import': 'Nhập KML/KMZ',
      'googleEarth.exportKml': 'Xuất KML',
      'googleEarth.exportKmz': 'Xuất KMZ',
      'googleEarth.open': 'Mở bằng Google Earth',
      'googleEarth.openSuccess': 'Đã mở tệp ranh giới.',
      'googleEarth.openUnavailable':
          'Không tìm thấy ứng dụng phù hợp để mở tệp.',
      'gps.preview.title': 'Xem trước đo GPS',
      'gps.start': 'Đo GPS',
      'gps.confirm': 'Áp dụng ranh giới GPS',
      'import.preview.title': 'Xem trước dữ liệu nhập',
      'import.warning.missingAgricoMetadata': 'Tệp không có metadata AGRICO.',
      'validation.required': 'Trường này là bắt buộc.',
      'attachment.addMetadata': 'Thêm ảnh / tài liệu',
      'landUse.agricultural': 'Nông nghiệp',
      'landUse.residential': 'Đất ở',
      'landUse.forest': 'Rừng',
      'landUse.pasture': 'Đồng cỏ',
      'landUse.mixed': 'Hỗn hợp',
      'landUse.other': 'Khác',
      'landCondition.unknown': 'Chưa rõ',
      'landCondition.unused': 'Chưa sử dụng',
      'landCondition.cultivated': 'Đang canh tác',
      'landCondition.degraded': 'Suy thoái',
      'landCondition.flooded': 'Ngập nước',
      'landCondition.other': 'Khác',
      'clearing.unknown': 'Chưa rõ',
      'clearing.notRequired': 'Không cần',
      'clearing.notStarted': 'Chưa phát quang',
      'clearing.partial': 'Một phần',
      'clearing.completed': 'Hoàn tất',
      'readiness.unknown': 'Chưa rõ',
      'readiness.notReady': 'Chưa sẵn sàng',
      'readiness.preparation': 'Đang chuẩn bị',
      'readiness.ready': 'Sẵn sàng',
    },
    'lo': {
      'app.name': 'AGRICO ERP',
      'app.tagline': 'ການຈັດການກະສິກຳອັດສະລິຍະ',
      'auth.username': 'ອີເມວ / ຊື່ຜູ້ໃຊ້',
      'auth.password': 'ລະຫັດຜ່ານ',
      'auth.forgotPassword': 'ລືມລະຫັດຜ່ານ?',
      'auth.signIn': 'ເຂົ້າລະບົບ',
      'auth.demoHint': '💡 (ກົດປຸ່ມເພື່ອເຂົ້າ Demo ໂດຍບໍ່ຕ້ອງໃສ່ລະຫັດ)',
      'common.loading': 'ກຳລັງໂຫຼດ…',
      'common.retry': 'ລອງໃໝ່',
      'common.cancel': 'ຍົກເລີກ',
      'common.save': 'ບັນທຶກ',
      'error.unauthorized': 'ທ່ານບໍ່ມີສິດເຮັດລາຍການນີ້.',
      'error.permissionDenied': 'ທ່ານບໍ່ມີສິດເຮັດລາຍການນີ້.',
      'landParcel.create.success': 'ສ້າງແປງດິນແລ້ວ.',
      'landParcel.update.success': 'ອັບເດດຂໍ້ມູນແປງດິນແລ້ວ.',
      'landParcel.error.notFound': 'ບໍ່ພົບແປງດິນ.',
      'landParcel.geometry.invalid': 'ເຂດແດນແປງດິນບໍ່ຖືກຕ້ອງ.',
      'landParcel.persistence.failed': 'ບໍ່ສາມາດບັນທຶກການປ່ຽນແປງໄດ້.',
      'landParcel.boundary.verifiedConfirmation':
          'ເຂດແດນນີ້ຖືກຢືນຢັນແລ້ວ. ກະລຸນາຢືນຢັນກ່ອນປ່ຽນແທນ.',
      'landParcel.boundary.replaceSuccess': 'ອັບເດດເຂດແດນແລ້ວ.',
      'landParcel.boundary.verifySuccess': 'ອັບເດດສະຖານະການຢືນຢັນແລ້ວ.',
      'landParcel.gps.invalidSource': 'ແຫຼ່ງຂໍ້ມູນ GPS ບໍ່ຖືກຕ້ອງ.',
      'landParcel.import.previewReady': 'ກຽມຕົວຢ່າງກ່ອນນຳເຂົ້າແລ້ວ.',
      'landParcel.import.failed': 'ບໍ່ສາມາດອ່ານໄຟລ໌ KML/KMZ.',
      'landParcel.export.success': 'ສົ່ງອອກໄຟລ໌ KML/KMZ ແລ້ວ.',
      'landParcel.export.failed': 'ບໍ່ສາມາດສົ່ງອອກ KML/KMZ.',
      'landParcel.preview.warning': 'ກະລຸນາກວດຄຳເຕືອນກ່ອນຢືນຢັນ.',
      'survey.household': 'ຄົວເຮືອນ',
      'survey.administrativeLocation': 'ທີ່ຢູ່ປົກຄອງ',
      'survey.landUse': 'ການນຳໃຊ້ທີ່ດິນ',
      'survey.landCondition': 'ສະພາບທີ່ດິນ',
      'survey.clearingStatus': 'ສະຖານະການຖາງ',
      'survey.readinessStatus': 'ຄວາມພ້ອມ',
      'survey.crop': 'ພືດປູກ',
      'survey.cropCondition': 'ສະພາບພືດ',
      'survey.quantityUnit': 'ຈຳນວນ ແລະ ຫົວໜ່ວຍ',
      'survey.record': 'ການສຳຫຼວດທີ່ດິນ',
      'survey.surveyor': 'ຜູ້ສຳຫຼວດ',
      'survey.attachment': 'ໄຟລ໌ແນບ',
      'survey.validation.invalid': 'ຂໍ້ມູນສຳຫຼວດບໍ່ຖືກຕ້ອງ.',
      'survey.persistence.failed': 'ບໍ່ສາມາດບັນທຶກຂໍ້ມູນສຳຫຼວດ.',
      'common.all': 'ທັງໝົດ',
      'common.active': 'ໃຊ້ງານ',
      'common.inactive': 'ບໍ່ໃຊ້ງານ',
      'common.edit': 'ແກ້ໄຂ',
      'common.remove': 'ລຶບ',
      'common.confirm': 'ຢືນຢັນ',
      'parcel.list.title': 'ລາຍການແປງດິນ',
      'parcel.list.empty': 'ຍັງບໍ່ມີແປງດິນ.',
      'parcel.list.error': 'ບໍ່ສາມາດໂຫຼດລາຍການແປງດິນ.',
      'parcel.detail.error': 'ບໍ່ສາມາດໂຫຼດລາຍລະອຽດແປງດິນ.',
      'parcel.search': 'ຄົ້ນຫາແປງດິນ',
      'parcel.filter.active': 'ສະຖານະ',
      'parcel.filter.verification': 'ການຢືນຢັນ',
      'parcel.create.action': 'ສ້າງແປງດິນ',
      'parcel.create.title': 'ສ້າງຂໍ້ມູນແປງດິນ',
      'parcel.edit.title': 'ແກ້ໄຂແປງດິນ',
      'parcel.code': 'ລະຫັດແປງ',
      'parcel.name': 'ຊື່ແປງດິນ',
      'parcel.section.identity': 'ຂໍ້ມູນແປງດິນ',
      'parcel.section.overview': 'ພາບລວມ',
      'parcel.section.boundary': 'ເຂດແດນ ແລະ ການວັດແທກ',
      'location.country': 'ປະເທດ',
      'location.province': 'ແຂວງ',
      'location.district': 'ເມືອງ',
      'location.village': 'ບ້ານ',
      'household.code': 'ລະຫັດຄົວເຮືອນ',
      'household.head': 'ຫົວໜ້າຄົວເຮືອນ',
      'household.phone': 'ໂທລະສັບ',
      'household.alternativeContact': 'ຕິດຕໍ່ອື່ນ',
      'geometry.areaM2': 'ເນື້ອທີ່ m²',
      'geometry.areaHa': 'ເນື້ອທີ່ ha',
      'geometry.perimeter': 'ຄວາມຍາວຮອບ',
      'geometry.centroid': 'ຈຸດສູນກາງ',
      'geometry.accuracy': 'ຄວາມຊັດເຈນ',
      'geometry.confidence': 'ຄວາມໝັ້ນໃຈ',
      'boundary.source': 'ແຫຼ່ງເຂດແດນ',
      'boundary.version': 'ສະບັບ',
      'boundary.history.title': 'ປະຫວັດເຂດແດນ',
      'boundary.source.gps': 'GPS',
      'boundary.source.googleEarth': 'Google Earth',
      'boundary.source.manual': 'ກຳນົດເອງ',
      'boundary.source.cad': 'CAD',
      'boundary.source.imported': 'ນຳເຂົ້າ',
      'verification.draft': 'ຮ່າງ',
      'verification.measured': 'ວັດແທກແລ້ວ',
      'verification.verified': 'ຢືນຢັນແລ້ວ',
      'verification.rejected': 'ຖືກປະຕິເສດ',
      'verification.confirm.title': 'ປ່ຽນເຂດແດນທີ່ຢືນຢັນແລ້ວ?',
      'crop.empty': 'ຍັງບໍ່ມີພືດ.',
      'crop.add': 'ເພີ່ມພືດ',
      'crop.edit': 'ແກ້ໄຂພືດ',
      'crop.type': 'ຊະນິດພືດ',
      'crop.quantity': 'ຈຳນວນ',
      'crop.unit': 'ຫົວໜ່ວຍ',
      'crop.condition.unknown': 'ບໍ່ຮູ້',
      'crop.condition.planned': 'ວາງແຜນ',
      'crop.condition.growing': 'ກຳລັງເຕີບໂຕ',
      'crop.condition.healthy': 'ດີ',
      'crop.condition.stressed': 'ບໍ່ແຂງແຮງ',
      'crop.condition.harvested': 'ເກັບກ່ຽວແລ້ວ',
      'survey.empty': 'ຍັງບໍ່ມີການສຳຫຼວດ.',
      'attachment.empty': 'ຍັງບໍ່ມີໄຟລ໌ແນບ.',
      'googleEarth.title': 'Google Earth',
      'googleEarth.import': 'ນຳເຂົ້າ KML/KMZ',
      'googleEarth.exportKml': 'ສົ່ງອອກ KML',
      'googleEarth.exportKmz': 'ສົ່ງອອກ KMZ',
      'googleEarth.open': 'ເປີດດ້ວຍ Google Earth',
      'googleEarth.openSuccess': 'ເປີດໄຟລ໌ເຂດແດນແລ້ວ.',
      'googleEarth.openUnavailable': 'ບໍ່ພົບແອັບທີ່ສາມາດເປີດໄຟລ໌ນີ້.',
      'gps.preview.title': 'ຕົວຢ່າງການວັດ GPS',
      'gps.start': 'ວັດແທກ GPS',
      'gps.confirm': 'ນຳໃຊ້ເຂດແດນ GPS',
      'import.preview.title': 'ຕົວຢ່າງກ່ອນນຳເຂົ້າ',
      'import.warning.missingAgricoMetadata': 'ໄຟລ໌ບໍ່ມີ metadata AGRICO.',
      'validation.required': 'ຈຳເປັນຕ້ອງປ້ອນຂໍ້ມູນນີ້.',
      'attachment.addMetadata': 'ເພີ່ມຮູບ / ເອກະສານ',
      'landUse.agricultural': 'ກະສິກຳ',
      'landUse.residential': 'ທີ່ຢູ່ອາໄສ',
      'landUse.forest': 'ປ່າໄມ້',
      'landUse.pasture': 'ທົ່ງຫຍ້າ',
      'landUse.mixed': 'ປະສົມ',
      'landUse.other': 'ອື່ນໆ',
      'landCondition.unknown': 'ບໍ່ຮູ້',
      'landCondition.unused': 'ຍັງບໍ່ໃຊ້',
      'landCondition.cultivated': 'ກຳລັງປູກຝັງ',
      'landCondition.degraded': 'ເສື່ອມໂຊມ',
      'landCondition.flooded': 'ນ້ຳຖ້ວມ',
      'landCondition.other': 'ອື່ນໆ',
      'clearing.unknown': 'ບໍ່ຮູ້',
      'clearing.notRequired': 'ບໍ່ຈຳເປັນ',
      'clearing.notStarted': 'ຍັງບໍ່ຖາງ',
      'clearing.partial': 'ບາງສ່ວນ',
      'clearing.completed': 'ສຳເລັດ',
      'readiness.unknown': 'ບໍ່ຮູ້',
      'readiness.notReady': 'ຍັງບໍ່ພ້ອມ',
      'readiness.preparation': 'ກຳລັງກຽມ',
      'readiness.ready': 'ພ້ອມ',
    },
    'en': {
      'app.name': 'AGRICO ERP',
      'app.tagline': 'Smart agriculture management',
      'auth.username': 'Email / Username',
      'auth.password': 'Password',
      'auth.forgotPassword': 'Forgot password?',
      'auth.signIn': 'SIGN IN',
      'auth.demoHint': '💡 (Tap to enter the demo without a password)',
      'common.loading': 'Loading…',
      'common.retry': 'Retry',
      'common.cancel': 'Cancel',
      'common.save': 'Save',
      'error.unauthorized': 'You do not have permission for this action.',
      'error.permissionDenied': 'You do not have permission for this action.',
      'landParcel.create.success': 'Land parcel created.',
      'landParcel.update.success': 'Land parcel details updated.',
      'landParcel.error.notFound': 'Land parcel not found.',
      'landParcel.geometry.invalid': 'The land parcel boundary is invalid.',
      'landParcel.persistence.failed':
          'The land parcel change could not be saved.',
      'landParcel.boundary.verifiedConfirmation':
          'This boundary is verified. Confirm before replacing it.',
      'landParcel.boundary.replaceSuccess': 'Land parcel boundary updated.',
      'landParcel.boundary.verifySuccess': 'Verification status updated.',
      'landParcel.gps.invalidSource': 'The GPS measurement source is invalid.',
      'landParcel.import.previewReady': 'Import preview is ready.',
      'landParcel.import.failed': 'The KML/KMZ file could not be read.',
      'landParcel.export.success': 'KML/KMZ export is ready.',
      'landParcel.export.failed': 'The KML/KMZ file could not be exported.',
      'landParcel.preview.warning': 'Review warnings before confirming.',
      'survey.household': 'Household',
      'survey.administrativeLocation': 'Administrative location',
      'survey.landUse': 'Land use',
      'survey.landCondition': 'Land condition',
      'survey.clearingStatus': 'Clearing status',
      'survey.readinessStatus': 'Readiness status',
      'survey.crop': 'Crop',
      'survey.cropCondition': 'Crop condition',
      'survey.quantityUnit': 'Quantity and unit',
      'survey.record': 'Land survey',
      'survey.surveyor': 'Surveyor',
      'survey.attachment': 'Attachment',
      'survey.validation.invalid': 'The survey data is invalid.',
      'survey.persistence.failed': 'The survey data could not be saved.',
      'common.all': 'All',
      'common.active': 'Active',
      'common.inactive': 'Inactive',
      'common.edit': 'Edit',
      'common.remove': 'Remove',
      'common.confirm': 'Confirm',
      'parcel.list.title': 'Land parcels',
      'parcel.list.empty': 'No land parcels yet.',
      'parcel.list.error': 'Land parcels could not be loaded.',
      'parcel.detail.error': 'Land parcel details could not be loaded.',
      'parcel.search': 'Search parcels',
      'parcel.filter.active': 'Status',
      'parcel.filter.verification': 'Verification',
      'parcel.create.action': 'Create parcel',
      'parcel.create.title': 'Create land parcel',
      'parcel.edit.title': 'Edit land parcel',
      'parcel.code': 'Parcel code',
      'parcel.name': 'Parcel name',
      'parcel.section.identity': 'Parcel information',
      'parcel.section.overview': 'Overview',
      'parcel.section.boundary': 'Boundary and measurement',
      'location.country': 'Country',
      'location.province': 'Province',
      'location.district': 'District',
      'location.village': 'Village / Ban',
      'household.code': 'Household code',
      'household.head': 'Head of household',
      'household.phone': 'Phone',
      'household.alternativeContact': 'Alternative contact',
      'geometry.areaM2': 'Area m²',
      'geometry.areaHa': 'Area ha',
      'geometry.perimeter': 'Perimeter',
      'geometry.centroid': 'Centroid',
      'geometry.accuracy': 'Accuracy',
      'geometry.confidence': 'Confidence',
      'boundary.source': 'Boundary source',
      'boundary.version': 'Version',
      'boundary.history.title': 'Boundary history',
      'boundary.source.gps': 'GPS',
      'boundary.source.googleEarth': 'Google Earth',
      'boundary.source.manual': 'Manual',
      'boundary.source.cad': 'CAD',
      'boundary.source.imported': 'Imported',
      'verification.draft': 'Draft',
      'verification.measured': 'Measured',
      'verification.verified': 'Verified',
      'verification.rejected': 'Rejected',
      'verification.confirm.title': 'Replace verified boundary?',
      'crop.empty': 'No crops.',
      'crop.add': 'Add crop',
      'crop.edit': 'Edit crop',
      'crop.type': 'Crop type',
      'crop.quantity': 'Quantity',
      'crop.unit': 'Unit',
      'crop.condition.unknown': 'Unknown',
      'crop.condition.planned': 'Planned',
      'crop.condition.growing': 'Growing',
      'crop.condition.healthy': 'Healthy',
      'crop.condition.stressed': 'Stressed',
      'crop.condition.harvested': 'Harvested',
      'survey.empty': 'No surveys.',
      'attachment.empty': 'No attachments.',
      'googleEarth.title': 'Google Earth',
      'googleEarth.import': 'Import KML/KMZ',
      'googleEarth.exportKml': 'Export KML',
      'googleEarth.exportKmz': 'Export KMZ',
      'googleEarth.open': 'Open in Google Earth',
      'googleEarth.openSuccess': 'Boundary file opened.',
      'googleEarth.openUnavailable':
          'No compatible app is available to open this file.',
      'gps.preview.title': 'GPS measurement preview',
      'gps.start': 'Measure with GPS',
      'gps.confirm': 'Apply GPS boundary',
      'import.preview.title': 'Import preview',
      'import.warning.missingAgricoMetadata':
          'This file has no AGRICO metadata.',
      'validation.required': 'This field is required.',
      'attachment.addMetadata': 'Add photo / document',
      'landUse.agricultural': 'Agricultural',
      'landUse.residential': 'Residential',
      'landUse.forest': 'Forest',
      'landUse.pasture': 'Pasture',
      'landUse.mixed': 'Mixed',
      'landUse.other': 'Other',
      'landCondition.unknown': 'Unknown',
      'landCondition.unused': 'Unused',
      'landCondition.cultivated': 'Cultivated',
      'landCondition.degraded': 'Degraded',
      'landCondition.flooded': 'Flooded',
      'landCondition.other': 'Other',
      'clearing.unknown': 'Unknown',
      'clearing.notRequired': 'Not required',
      'clearing.notStarted': 'Not started',
      'clearing.partial': 'Partial',
      'clearing.completed': 'Completed',
      'readiness.unknown': 'Unknown',
      'readiness.notReady': 'Not ready',
      'readiness.preparation': 'Preparation',
      'readiness.ready': 'Ready',
    },
  };

  String text(String key) {
    final languageCode = _catalogue.containsKey(locale.languageCode)
        ? locale.languageCode
        : 'vi';
    return _catalogue[languageCode]?[key] ?? _catalogue['vi']?[key] ?? key;
  }

  @visibleForTesting
  static Set<String> keysFor(Locale locale) =>
      _catalogue[locale.languageCode]?.keys.toSet() ?? const {};
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => AppLocalizations.supportedLocales.any(
    (supported) => supported.languageCode == locale.languageCode,
  );

  @override
  Future<AppLocalizations> load(Locale locale) =>
      SynchronousFuture(AppLocalizations(locale));

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

extension AppLocalizationsContext on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}
